cgdsa-c: dllist.h File Reference
dllist.h File Reference
#include <stddef.h>
Typedefs
typedef struct __dllist_t dllist_t
A pointer to a structure used for a single node in the list.
typedef int(* dllist_compare)(const void *a1, const void *a2)
A compare function used for insersion, sort, and find.
typedef int(* dllist_free)(void *a1)
A free function used for node removal.
typedef int(* dllist_func)(void *arg)
A function used to apply a transformation to each value associated with each node.
Functions
int dllist_free_node (void *arg)
A convenience function for the developer.
dllist_t * dllist_create (dllist_compare compare, dllist_free free)
Create a new list.
int dllist_clear (dllist_t *list)
Empty a list by destroying all of it's nodes.
dllist_t * dllist_apply (dllist_t *list, dllist_func arg)
Apply a function to every node in the list.
dllist_t * dllist_destroy (dllist_t *list)
Destroy a list.
dllist_t * dllist_sentinel (dllist_t *node)
Given a node from some list, return the sentinel (header node)
dllist_t * dllist_insert_before (dllist_t *node, void *value)
Create a new node containing value and insert it before node.
dllist_t * dllist_insert_after (dllist_t *node, void *value)
Create a new node containing value and insert it after node.
dllist_t * dllist_insert (dllist_t *list, void *value)
Create a new node containing value and insert it into the list.
dllist_t * dllist_push_front (dllist_t *list, void *value)
Create a new node containing value and insert it at the beginning of the list.
dllist_t * dllist_push_back (dllist_t *list, void *value)
Create a new node containing value and insert it at the end of the list.
dllist_t * dllist_clone (dllist_t *list)
Make a copy of a list.
dllist_t * dllist_find (dllist_t *list, void *value)
Search for the value in the list.
void * dllist_value (dllist_t *node)
Return the value from a node.
int dllist_remove (dllist_t *node)
Remove a node from a list.
dllist_t * dllist_first (dllist_t *list)
Return the first node in a list.
dllist_t * dllist_last (dllist_t *list)
Return the last node in the list.
dllist_t * dllist_next (dllist_t *node)
Return the next node in the list.
dllist_t * dllist_prev (dllist_t *node)
Return the previous node in the list.
int dllists_are_identical (dllist_t *list1, dllist_t *list2)
Discern if two lists are identical.
size_t dllist_size (dllist_t *list)
Return the number of nodes in the list.
int dllist_sort (dllist_t *list)
Sort the list using a quicksort algorithm.
int dllist_detach_node (dllist_t *list, dllist_t *node)
Remove a node from the list.
int dllist_attach_node (dllist_t *list, dllist_t *node)
Attach a node to the end of a list.
Typedef Documentation
typedef int(* dllist_compare)(const void *a1, const void *a2)
A compare function used for insersion, sort, and find.
This function should compare the two values given as const void * pointers, and return:
if (left < right) return -1
if (left > right) return 1
otherwise return 0
Definition at line 55 of file dllist.h.
typedef int(* dllist_free)(void *a1)
A free function used for node removal.
This function should properly destroy a value, if necessary. It should return 1 on success, and 0 on failure.
Definition at line 61 of file dllist.h.
typedef int(* dllist_func)(void *arg)
A function used to apply a transformation to each value associated with each node.
Definition at line 66 of file dllist.h.
typedef struct __dllist_t dllist_t
A pointer to a structure used for a single node in the list.
It contains a void * pointer to an associated value.
Definition at line 47 of file dllist.h.
Function Documentation
dllist_t* dllist_apply (dllist_t * list, dllist_func arg)
Apply a function to every node in the list.
Returns:
Success: NULL
Failure: dllist_t * pointer to the node for which dllist_func() failed
int dllist_attach_node (dllist_t * list, dllist_t * node)
Attach a node to the end of a list.
Returns:
Success: 1
Failure: 0
Definition at line 416 of file dllist.c.
References __dllist_is_sentinel(), __dllist_t::compare, dllist_sentinel(), __dllist_t::free, __dllist_t::next, __dllist_t::prev, __dllist_t::sentinel, and __dllist_t::size.
Referenced by dllist_sort(), and main().
int dllist_clear (dllist_t * list)
Empty a list by destroying all of it's nodes.
Return value:
Success: 1
Failure: 0
Definition at line 282 of file dllist.c.
References dllist_first(), dllist_remove(), dllist_sentinel(), and dllist_size().
dllist_t* dllist_clone (dllist_t * list)
Make a copy of a list.
Return value:
Success: dllist_t * pointer to a new list
Failure: NULL
Notes: Be aware that cloning a list merely copies the value pointers. It does not create copies of what the value pointers point to.
Definition at line 227 of file dllist.c.
References __dllist_t::compare, dllist_create(), dllist_destroy(), dllist_first(), dllist_next(), dllist_push_back(), dllist_sentinel(), __dllist_t::free, and __dllist_t::value.
Referenced by main().
dllist_t* dllist_create (dllist_compare compare, dllist_free free)
Create a new list.
Compare is a pointer to a function used to compare void * values. Compare may be NULL. Free is a pointer to a function to call when destroying nodes. Free is responsible for properly releasing any memory used for the value stored by the node. Free may be NULL.
Definition at line 56 of file dllist.c.
References compare(), __dllist_t::compare, __dllist_t::free, __dllist_t::next, __dllist_t::prev, __dllist_t::sentinel, __dllist_t::size, and __dllist_t::value.
Referenced by dllist_clone(), dllist_sort(), main(), and str_split().
dllist_t* dllist_destroy (dllist_t * list)
Destroy a list.
Returns: NULL
Definition at line 94 of file dllist.c.
References dllist_first(), dllist_remove(), dllist_sentinel(), dllist_size(), and __dllist_t::free.
Referenced by dllist_clone(), dllist_sort(), main(), and str_split().
int dllist_detach_node (dllist_t * list, dllist_t * node)
Remove a node from the list.
Returns:
Success: 1
Failure: 0
Definition at line 400 of file dllist.c.
References __dllist_is_sentinel(), __dllist_t::compare, dllist_sentinel(), __dllist_t::free, __dllist_t::next, __dllist_t::prev, __dllist_t::sentinel, and __dllist_t::size.
Referenced by dllist_sort(), and main().
dllist_t* dllist_find (dllist_t * list, void * value)
Search for the value in the list.
Returns:
Success: dllist_t * pointer to the found node
Failure: NULL
Notes: If the list was created with a NULL compare function pointer, then only the addresses of the value pointer is compares with the value pointer of the nodes. If the list has a non-NULL compare function pointer, then the compare function is used.
Definition at line 247 of file dllist.c.
References __dllist_t::compare, dllist_first(), dllist_next(), dllist_sentinel(), and __dllist_t::value.
Referenced by main().
dllist_t* dllist_first (dllist_t * list)
Return the first node in a list.
Returns:
Success: dllist_t * pointer to the first node
Failure: NULL – the list is empty
Definition at line 293 of file dllist.c.
References __dllist_is_sentinel(), dllist_sentinel(), and __dllist_t::next.
Referenced by dllist_apply(), dllist_clear(), dllist_clone(), dllist_destroy(), dllist_find(), dllist_insert(), dllist_sort(), dllists_are_identical(), main(), and str_join().
int dllist_free_node (void * arg)
A convenience function for the developer.
This function applies free() to the value of a node.
Definition at line 73 of file dllist.c.
References __dllist_t::free.
Referenced by main(), and str_split().
dllist_t* dllist_insert (dllist_t * list, void * value)
Create a new node containing value and insert it into the list.
If the list was created with a non-NULL value for a compare function, then dllist_insert() acts like insertion sort, inserting the new node into it's correct position in the list.
Returns:
Success: dllist_t * pointer to the newly created node
Failure: NULL
Definition at line 175 of file dllist.c.
References __dllist_is_sentinel(), __dllist_t::compare, dllist_first(), dllist_insert_before(), dllist_sentinel(), __dllist_t::next, and __dllist_t::value.
Referenced by main().
dllist_t* dllist_insert_after (dllist_t * node, void * value)
Create a new node containing value and insert it after node.
Returns:
Success: dllist_t * pointer to the newly created node
Failure: NULL
Definition at line 156 of file dllist.c.
References __dllist_make_new_node(), __dllist_t::next, __dllist_t::prev, __dllist_t::sentinel, and __dllist_t::size.
Referenced by dllist_push_front(), and main().
dllist_t* dllist_insert_before (dllist_t * node, void * value)
Create a new node containing value and insert it before node.
Returns:
Success: dllist_t * pointer to the newly created node
Failure: NULL
Definition at line 137 of file dllist.c.
References __dllist_make_new_node(), __dllist_t::next, __dllist_t::prev, __dllist_t::sentinel, and __dllist_t::size.
Referenced by dllist_insert(), dllist_push_back(), and main().
dllist_t* dllist_last (dllist_t * list)
Return the last node in the list.
Returns:
Success: dllist_t * pointer to the last node
Failure: NULL – the list is empty
Definition at line 301 of file dllist.c.
References __dllist_is_sentinel(), dllist_sentinel(), and __dllist_t::prev.
Referenced by main().
dllist_t* dllist_next (dllist_t * node)
Return the next node in the list.
Returns:
Success: dllist_t * pointer to the next node
Failure: NULL – you have reached the end of the list
Definition at line 309 of file dllist.c.
References __dllist_is_sentinel(), and __dllist_t::next.
Referenced by dllist_apply(), dllist_clone(), dllist_find(), dllists_are_identical(), main(), and str_join().
dllist_t* dllist_prev (dllist_t * node)
Return the previous node in the list.
Returns:
Success: dllist_t * pointer to the previous node
Failure: NULL – you have reached the beginning of the list
Definition at line 317 of file dllist.c.
References __dllist_is_sentinel(), and __dllist_t::prev.
Referenced by main().
dllist_t* dllist_push_back (dllist_t * list, void * value)
Create a new node containing value and insert it at the end of the list.
Returns:
Success: dllist_t * pointer to the newly created node
Failure: NULL
Definition at line 216 of file dllist.c.
References dllist_insert_before(), and dllist_sentinel().
Referenced by dllist_clone(), main(), and str_split().
dllist_t* dllist_push_front (dllist_t * list, void * value)
Create a new node containing value and insert it at the beginning of the list.
Returns:
Success: dllist_t * pointer to the newly created node
Failure: NULL
Definition at line 205 of file dllist.c.
References dllist_insert_after(), and dllist_sentinel().
Referenced by main().
int dllist_remove (dllist_t * node)
Remove a node from a list.
Returns:
Success: 1
Failure: 0
Definition at line 270 of file dllist.c.
References __dllist_is_sentinel(), __dllist_t::free, __dllist_t::next, __dllist_t::prev, __dllist_t::sentinel, __dllist_t::size, and __dllist_t::value.
Referenced by dllist_clear(), dllist_destroy(), and main().
dllist_t* dllist_sentinel (dllist_t * node)
Given a node from some list, return the sentinel (header node)
Returns:
Success: dllist_t * pointer to the list's sentinel
Failure: NULL
Definition at line 110 of file dllist.c.
References __dllist_t::sentinel.
Referenced by dllist_apply(), dllist_attach_node(), dllist_clear(), dllist_clone(), dllist_destroy(), dllist_detach_node(), dllist_find(), dllist_first(), dllist_insert(), dllist_last(), dllist_push_back(), dllist_push_front(), and main().
size_t dllist_size (dllist_t * list)
Return the number of nodes in the list.
Returns:
Success: size_t number of nodes in the list (a 0 or greater value)
Failure: 0 – if the list pointer is NULL
Definition at line 360 of file dllist.c.
References __dllist_t::sentinel, and __dllist_t::size.
Referenced by dllist_clear(), dllist_destroy(), dllist_sort(), and main().
int dllist_sort (dllist_t * list)
Sort the list using a quicksort algorithm.
Returns:
Success: 1
Failure: 0
Definition at line 434 of file dllist.c.
References __dllist_t::compare, dllist_attach_node(), dllist_create(), dllist_destroy(), dllist_detach_node(), dllist_first(), dllist_size(), dllist_sort(), dllist_value(), and __dllist_t::free.
Referenced by dllist_sort(), and main().
void* dllist_value (dllist_t * node)
Return the value from a node.
Returns: void *
Definition at line 264 of file dllist.c.
References __dllist_t::value.
Referenced by dllist_apply(), dllist_sort(), main(), and str_join().
int dllists_are_identical (dllist_t * list1, dllist_t * list2)
Discern if two lists are identical.
Returns:
Success: 1 – the lists are identical
Failure: 0 – the lists differ
Notes:
If the lists were created with NULL compare function pointers, then only the addresses of the nodes values are compared. Otherwise, the compare function will be used.
The comparison algorithm
If both lists are NULL, then return 1
If one list is NULL and the other non-NULL, then return 0
If the two lists do not have the same compare function pointer, return 0
If the nth node from list1 != the nth node from list2, return 0
If the lists are not the same size, return 0
Otherwise, return 1
Definition at line 325 of file dllist.c.
References __dllist_t::compare, dllist_first(), dllist_next(), and __dllist_t::value.
Referenced by main().