cgdsa-c: mem.h File Reference
mem.h File Reference
Functions
void * mem_alloc (size_t size)
Mem.
void * mem_realloc (void *ptr, size_t size)
(Re)allocate size bytes of memory
size_t mem_size (void *ptr)
Return the number of bytes allocated for ptr.
void * mem_begin (void *ptr)
Return the beginning of the ptr's chunk of memory, if found.
void * mem_end (void *ptr)
Return an pointer to the end of ptr's chunk of memory.
void * mem_free (void *ptr)
Release memory allocated to ptr.
unsigned long long mem_total (void)
Return the total number of bytes allocated my mem_alloc()/mem_realloc()
Function Documentation
void* mem_alloc (size_t size)
Mem.
A very simple memory map that tracks memory allocation size. Allocate size bytes of memory
Arguments:
size_t size – Number of bytes to allocate
Return value:
Success: void * – pointer to memory
Failure: NULL
Definition at line 196 of file mem.c.
References LOCK, mf__mem_alloc(), and UNLOCK.
Referenced by test_001(), test_002(), test_003(), and test_004().
void* mem_begin (void * ptr)
Return the beginning of the ptr's chunk of memory, if found.
Arguments:
void * ptr – A pointer to a location in memory
Return value:
Success: void * – pointer to the begining of the memory segment
Failure: NULL
Definition at line 206 of file mem.c.
References LOCK, mf__mem_begin(), and UNLOCK.
Referenced by str_append(), str_assign(), str_caseless_rfind(), str_erase(), str_insert(), str_prepend(), str_replace(), str_reserve(), str_rfind(), str_rfind_char(), str_rfind_not_char(), str_shrink_reserve(), and test_004().
void* mem_end (void * ptr)
Return an pointer to the end of ptr's chunk of memory.
Arguments:
void * ptr – A pointer to a location in memory
Return value:
Success: void * – pointer to the end of the memory segment
Failure: NULL
Definition at line 216 of file mem.c.
References LOCK, mf__mem_end(), and UNLOCK.
Referenced by str_reserve(), test_001(), test_002(), and test_003().
void* mem_free (void * ptr)
Release memory allocated to ptr.
Arguments:
void * ptr – A pointer to a location in memory
Return value: NULL
NOTES:
Ptr need not be the head of the memory segment, but may be a pointer to a location within a memory segment
Definition at line 246 of file mem.c.
References LOCK, mf__mem_free(), and UNLOCK.
Referenced by str_destroy(), test_001(), test_002(), test_003(), and test_004().
void* mem_realloc (void * ptr, size_t size)
(Re)allocate size bytes of memory
Arguments:
void * ptr – A pointer to a location in memory
size_t size – Total number of bytes requested
Return value:
Succcess: void * – pointer to the head of the memory segment (which may have changed due to (re)allocation)
Failure: NULL
NOTES:
If ptr is NULL, then mem_realloc() acts like mem_alloc()
Ptr need not be the head of the memory segment, but may be a pointer to a location within a memory segment
Definition at line 226 of file mem.c.
References LOCK, mf__mem_realloc(), and UNLOCK.
Referenced by str_reserve(), and test_002().
size_t mem_size (void * ptr)
Return the number of bytes allocated for ptr.
Arguments:
void * ptr – A pointer to a location in memory
Return value:
Success: size_t value > 0
Failure: 0
NOTES:
Ptr need not be the head of the memory segment, but may be a pointer to a location within a memory segment
Definition at line 236 of file mem.c.
References LOCK, mf__mem_size(), and UNLOCK.
Referenced by str_capacity(), test_001(), test_002(), and test_003().
unsigned long long mem_total (void)
Return the total number of bytes allocated my mem_alloc()/mem_realloc()
Arguments: none
Return value:
unsigned long long – The number of bytes currently allocated
Definition at line 256 of file mem.c.
References LOCK, mf__mem_total(), and UNLOCK.