cgdsa-c: mem.c File Reference
mem.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include "mem.h"
#include "rbtree.h"
Macros
#define LOCK
#define UNLOCK
Functions
int mf__mem_compare (const void *a1, const void *a2)
int mf__mem_init (void)
void * mf__mem_alloc (size_t size)
void * mf__mem_begin (void *ptr)
void * mf__mem_end (void *ptr)
size_t mf__mem_size (void *ptr)
void * mf__mem_free (void *ptr)
void * mf__mem_realloc (void *ptr, size_t size)
unsigned long long mf__mem_total (void)
void * mem_alloc (size_t size)
Mem.
void * mem_begin (void *ptr)
Return the beginning of the ptr's chunk of memory, if found.
void * mem_end (void *ptr)
Return an pointer to the end of ptr's chunk of memory.
void * mem_realloc (void *ptr, size_t size)
(Re)allocate size bytes of memory
size_t mem_size (void *ptr)
Return the number of bytes allocated for ptr.
void * mem_free (void *ptr)
Release memory allocated to ptr.
unsigned long long mem_total (void)
Return the total number of bytes allocated my mem_alloc()/mem_realloc()
Variables
rbtree_t * __mem_map = NULL
unsigned long long __mem_total = 0
Macro Definition Documentation
#define LOCK
Definition at line 57 of file mem.c.
Referenced by mem_alloc(), mem_begin(), mem_end(), mem_free(), mem_realloc(), mem_size(), and mem_total().
#define UNLOCK
Definition at line 58 of file mem.c.
Referenced by mem_alloc(), mem_begin(), mem_end(), mem_free(), mem_realloc(), mem_size(), and mem_total().
Function Documentation
void* mem_alloc (size_t size)
Mem.
A very simple memory map that tracks memory allocation size. Allocate size bytes of memory
Arguments:
size_t size – Number of bytes to allocate
Return value:
Success: void * – pointer to memory
Failure: NULL
Definition at line 196 of file mem.c.
References LOCK, mf__mem_alloc(), and UNLOCK.
Referenced by test_001(), test_002(), test_003(), and test_004().
void* mem_begin (void * ptr)
Return the beginning of the ptr's chunk of memory, if found.
Arguments:
void * ptr – A pointer to a location in memory
Return value:
Success: void * – pointer to the begining of the memory segment
Failure: NULL
Definition at line 206 of file mem.c.
References LOCK, mf__mem_begin(), and UNLOCK.
Referenced by str_append(), str_assign(), str_caseless_rfind(), str_erase(), str_insert(), str_prepend(), str_replace(), str_reserve(), str_rfind(), str_rfind_char(), str_rfind_not_char(), str_shrink_reserve(), and test_004().
void* mem_end (void * ptr)
Return an pointer to the end of ptr's chunk of memory.
Arguments:
void * ptr – A pointer to a location in memory
Return value:
Success: void * – pointer to the end of the memory segment
Failure: NULL
Definition at line 216 of file mem.c.
References LOCK, mf__mem_end(), and UNLOCK.
Referenced by str_reserve(), test_001(), test_002(), and test_003().
void* mem_free (void * ptr)
Release memory allocated to ptr.
Arguments:
void * ptr – A pointer to a location in memory
Return value: NULL
NOTES:
Ptr need not be the head of the memory segment, but may be a pointer to a location within a memory segment
Definition at line 246 of file mem.c.
References LOCK, mf__mem_free(), and UNLOCK.
Referenced by str_destroy(), test_001(), test_002(), test_003(), and test_004().
void* mem_realloc (void * ptr, size_t size)
(Re)allocate size bytes of memory
Arguments:
void * ptr – A pointer to a location in memory
size_t size – Total number of bytes requested
Return value:
Succcess: void * – pointer to the head of the memory segment (which may have changed due to (re)allocation)
Failure: NULL
NOTES:
If ptr is NULL, then mem_realloc() acts like mem_alloc()
Ptr need not be the head of the memory segment, but may be a pointer to a location within a memory segment
Definition at line 226 of file mem.c.
References LOCK, mf__mem_realloc(), and UNLOCK.
Referenced by str_reserve(), and test_002().
size_t mem_size (void * ptr)
Return the number of bytes allocated for ptr.
Arguments:
void * ptr – A pointer to a location in memory
Return value:
Success: size_t value > 0
Failure: 0
NOTES:
Ptr need not be the head of the memory segment, but may be a pointer to a location within a memory segment
Definition at line 236 of file mem.c.
References LOCK, mf__mem_size(), and UNLOCK.
Referenced by str_capacity(), test_001(), test_002(), and test_003().
unsigned long long mem_total (void)
Return the total number of bytes allocated my mem_alloc()/mem_realloc()
Arguments: none
Return value:
unsigned long long – The number of bytes currently allocated
Definition at line 256 of file mem.c.
References LOCK, mf__mem_total(), and UNLOCK.
void* mf__mem_alloc (size_t size)
Definition at line 79 of file mem.c.
References __mem_total, __dllist_t::free, mf__mem_init(), rbtree_insert(), and __dllist_t::size.
Referenced by mem_alloc().
void* mf__mem_begin (void * ptr)
Definition at line 100 of file mem.c.
References mf__mem_init(), rbtree_key(), rbtree_left(), rbtree_right(), rbtree_top(), and rbtree_value().
Referenced by mem_begin(), mf__mem_end(), mf__mem_free(), mf__mem_realloc(), and mf__mem_size().
int mf__mem_compare (const void * a1, const void * a2)
Definition at line 61 of file mem.c.
Referenced by mf__mem_init().
void* mf__mem_end (void * ptr)
Definition at line 121 of file mem.c.
References mf__mem_begin(), mf__mem_init(), rbtree_find(), and rbtree_value().
Referenced by mem_end().
void* mf__mem_free (void * ptr)
Definition at line 147 of file mem.c.
References __mem_total, __dllist_t::free, mf__mem_begin(), mf__mem_init(), mf__mem_size(), rbtree_find(), and rbtree_remove().
Referenced by mem_free(), and mf__mem_realloc().
int mf__mem_init (void)
Definition at line 68 of file mem.c.
References mf__mem_compare(), and rbtree_create().
Referenced by mf__mem_alloc(), mf__mem_begin(), mf__mem_end(), mf__mem_free(), mf__mem_realloc(), and mf__mem_size().
void* mf__mem_realloc (void * ptr, size_t size)
Definition at line 165 of file mem.c.
References __mem_total, __dllist_t::free, mf__mem_begin(), mf__mem_free(), mf__mem_init(), mf__mem_size(), rbtree_insert(), and __dllist_t::size.
Referenced by mem_realloc().
size_t mf__mem_size (void * ptr)
Definition at line 133 of file mem.c.
References mf__mem_begin(), mf__mem_init(), rbtree_find(), rbtree_value(), and __dllist_t::size.
Referenced by mem_size(), mf__mem_free(), and mf__mem_realloc().
unsigned long long mf__mem_total (void)
Definition at line 191 of file mem.c.
References __mem_total.
Referenced by mem_total().
Variable Documentation
rbtree_t* __mem_map = NULL
Definition at line 48 of file mem.c.
unsigned long long __mem_total = 0
Definition at line 49 of file mem.c.
Referenced by mf__mem_alloc(), mf__mem_free(), mf__mem_realloc(), and mf__mem_total().