cgdsa-c: rbtree.c File Reference
rbtree.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include "rbtree.h"
Data Structures
struct __rbnode_t
struct __rbtree_t
Macros
#define __rbtree_verify_properties(t)
Typedefs
typedef struct __rbnode_t rbnode_t
typedef struct __rbtree_t rbtree_t
Enumerations
enum rbcolor { RED, BLACK }
Functions
rbnode_t * __rbtree_grandparent (rbnode_t *n)
rbnode_t * __rbtree_sibling (rbnode_t *n)
rbnode_t * __rbtree_uncle (rbnode_t *n)
enum rbcolor __rbnode_t_color (rbnode_t *n)
rbtree_t * rbtree_create (rbtree_compare compare, rbtree_free free)
Create a new tree.
int rbtree_clear (rbtree_t *t)
Empty the tree by destroying all of it's nodes.
rbnode_t * __rbtree_new_node (void *key, void *value, enum rbcolor color, rbnode_t *left, rbnode_t *right)
rbnode_t * rbtree_find (rbtree_t *t, void *key)
Given a tree and a key, search the tree for a node with the given key.
void __rbtree_replace_node (rbtree_t *t, rbnode_t *oldn, rbnode_t *newn)
void __rbtree_rotate_left (rbtree_t *t, rbnode_t *n)
void __rbtree_rotate_right (rbtree_t *t, rbnode_t *n)
void __rbtree_insert_case1 (rbtree_t *t, rbnode_t *n)
void __rbtree_insert_case2 (rbtree_t *t, rbnode_t *n)
void __rbtree_insert_case3 (rbtree_t *t, rbnode_t *n)
void __rbtree_insert_case4 (rbtree_t *t, rbnode_t *n)
void __rbtree_insert_case5 (rbtree_t *t, rbnode_t *n)
rbnode_t * rbtree_attach_node (rbtree_t *t, rbnode_t *node)
Attach a node to the tree.
int rbtree_insert (rbtree_t *t, void *key, void *value)
Create a new node with the given key/value pair, and insert it into the tree.
rbnode_t * __rbtree_maximum_node (rbnode_t *n)
void __rbtree_delete_case1 (rbtree_t *t, rbnode_t *n)
void __rbtree_delete_case2 (rbtree_t *t, rbnode_t *n)
void __rbtree_delete_case3 (rbtree_t *t, rbnode_t *n)
void __rbtree_delete_case4 (rbtree_t *t, rbnode_t *n)
void __rbtree_delete_case5 (rbtree_t *t, rbnode_t *n)
void __rbtree_delete_case6 (rbtree_t *t, rbnode_t *n)
rbnode_t * rbtree_detach_node (rbtree_t *t, rbnode_t *n)
Detach the given node from the tree.
int rbtree_remove (rbtree_t *t, rbnode_t *n)
Given a tree and a node, remove the node from the tree.
size_t rbtree_size (rbtree_t *t)
Return the number of nodes in the tree.
rbnode_t * __rbtree_apply_function (rbnode_t *n, rbtree_func func)
void __rbtree_destroy_nodes (rbtree_t *t, rbnode_t *n)
rbtree_t * rbtree_destroy (rbtree_t *t)
Destroy a tree and free all nodes, keys, and values.
int __rbtree_clone_node (rbtree_t *t, rbnode_t *n)
rbtree_t * rbtree_clone (rbtree_t *t)
Make a copy of a tree.
rbnode_t * rbtree_apply (rbtree_t *t, rbtree_func func)
Apply a transformation to each value of each node in the tree.
int __rbtree_write_gv_node (rbnode_t *n, FILE *fout, int(*write_node_key)(FILE *fout, void *key), int(*write_node_value)(FILE *fout, void *value))
int rbtree_write_gv (rbtree_t *t, char *filename, int(*write_node_key)(FILE *fout, void *key), int(*write_node_value)(FILE *fout, void *value))
Write a tree as a graphviz dot file.
void * rbtree_key (rbnode_t *n)
Return the key from a node.
void * rbtree_value (rbnode_t *n)
Return the value from a node.
rbnode_t * rbtree_top (rbtree_t *t)
Return the root node of a tree.
rbnode_t * rbtree_left (rbnode_t *n)
Return the left child of a node.
rbnode_t * rbtree_right (rbnode_t *n)
Return the right child of a node.
rbnode_t * rbtree_parent (rbnode_t *n)
Return the parent node of a node.
rbnode_t * rbtree_in_order_first (rbtree_t *t)
Given a tree, return the first node for in-order traversal.
rbnode_t * rbtree_in_order_last (rbtree_t *t)
Given a tree, return the first node for reverse in-order traversal.
rbnode_t * rbtree_in_order_next (rbnode_t *n)
Given a node, return the next node via in-order traversal.
rbnode_t * rbtree_in_order_prev (rbnode_t *n)
Given a node, return the previous node via reverse in-order traversal.
rbnode_t * rbtree_pre_order_first (rbtree_t *t)
Given a tree, return the first node for pre-order traversal.
rbnode_t * rbtree_pre_order_last (rbtree_t *t)
Given a tree, return the first node for reverse pre-order traversal.
rbnode_t * rbtree_pre_order_next (rbnode_t *n)
Given a node, return the next node via pre-order traversal.
rbnode_t * rbtree_pre_order_prev (rbnode_t *n)
Given a node, return the previous node via reverse in-order traversal.
rbnode_t * rbtree_post_order_first (rbtree_t *t)
Given a tree, return the first node for post-order traversal.
rbnode_t * rbtree_post_order_last (rbtree_t *t)
Given a tree, return the first node for reverse post-order traversal.
rbnode_t * rbtree_post_order_next (rbnode_t *n)
Given a node, return the next node via post-order traversal.
rbnode_t * rbtree_post_order_prev (rbnode_t *n)
Given a node, return the previous node via reverse post-order traversal.
int rbtrees_are_identical (rbtree_t *t1, rbtree_t *t2)
Determine if two trees are identical.
rbnode_t * rbtree_level_order_first (rbtree_t *t)
Given a tree, return the first node for level-order traversal.
size_t __rbnode_t_depth (rbnode_t *n)
rbnode_t * rbtree_level_order_last (rbtree_t *t)
Given a tree, return the first node for reverse level-order traversal.
rbnode_t * rbtree_level_order_next (rbnode_t *n)
Given a node, return the next node via level-order traversal.
rbnode_t * rbtree_level_order_prev (rbnode_t *n)
Given a node, return the previous node via reverse level-order traversal.
Macro Definition Documentation
#define __rbtree_verify_properties (t)
Definition at line 150 of file rbtree.c.
Referenced by rbtree_attach_node(), rbtree_create(), and rbtree_detach_node().
Typedef Documentation
typedef struct __rbnode_t rbnode_t
typedef struct __rbtree_t rbtree_t
Enumeration Type Documentation
enum rbcolor
Enumerator
RED
BLACK
Definition at line 43 of file rbtree.c.
Function Documentation
enum rbcolor __rbnode_t_color (rbnode_t * n)
Definition at line 87 of file rbtree.c.
References BLACK, and __rbnode_t::color.
Referenced by __rbtree_delete_case2(), __rbtree_delete_case3(), __rbtree_delete_case4(), __rbtree_delete_case5(), __rbtree_delete_case6(), __rbtree_insert_case2(), __rbtree_insert_case3(), and rbtree_detach_node().
size_t __rbnode_t_depth (rbnode_t * n)
Definition at line 1090 of file rbtree.c.
References rbtree_parent().
Referenced by rbtree_level_order_last(), rbtree_level_order_next(), and rbtree_level_order_prev().
rbnode_t* __rbtree_apply_function (rbnode_t * n, rbtree_func func)
Definition at line 637 of file rbtree.c.
References __rbnode_t::key, __rbnode_t::left, __rbnode_t::right, and __rbnode_t::value.
Referenced by rbtree_apply().
int __rbtree_clone_node (rbtree_t * t, rbnode_t * n)
Definition at line 674 of file rbtree.c.
References rbtree_insert(), rbtree_key(), rbtree_left(), rbtree_right(), and rbtree_value().
Referenced by rbtree_clone().
void __rbtree_delete_case1 (rbtree_t * t, rbnode_t * n)
Definition at line 491 of file rbtree.c.
References __rbtree_delete_case2(), and __rbnode_t::parent.
Referenced by __rbtree_delete_case3(), and rbtree_detach_node().
void __rbtree_delete_case2 (rbtree_t * t, rbnode_t * n)
Definition at line 499 of file rbtree.c.
References __rbnode_t_color(), __rbtree_delete_case3(), __rbtree_rotate_left(), __rbtree_rotate_right(), __rbtree_sibling(), BLACK, __rbnode_t::color, __rbnode_t::left, __rbnode_t::parent, and RED.
Referenced by __rbtree_delete_case1().
void __rbtree_delete_case3 (rbtree_t * t, rbnode_t * n)
Definition at line 512 of file rbtree.c.
References __rbnode_t_color(), __rbtree_delete_case1(), __rbtree_delete_case4(), __rbtree_sibling(), BLACK, __rbnode_t::color, __rbnode_t::parent, and RED.
Referenced by __rbtree_delete_case2().
void __rbtree_delete_case4 (rbtree_t * t, rbnode_t * n)
Definition at line 528 of file rbtree.c.
References __rbnode_t_color(), __rbtree_delete_case5(), __rbtree_sibling(), BLACK, __rbnode_t::color, __rbnode_t::parent, and RED.
Referenced by __rbtree_delete_case3().
void __rbtree_delete_case5 (rbtree_t * t, rbnode_t * n)
Definition at line 544 of file rbtree.c.
References __rbnode_t_color(), __rbtree_delete_case6(), __rbtree_rotate_left(), __rbtree_rotate_right(), __rbtree_sibling(), BLACK, __rbnode_t::color, __rbnode_t::left, __rbnode_t::parent, RED, and __rbnode_t::right.
Referenced by __rbtree_delete_case4().
void __rbtree_delete_case6 (rbtree_t * t, rbnode_t * n)
Definition at line 571 of file rbtree.c.
References __rbnode_t_color(), __rbtree_rotate_left(), __rbtree_rotate_right(), __rbtree_sibling(), BLACK, __rbnode_t::color, __rbnode_t::left, __rbnode_t::parent, RED, and __rbnode_t::right.
Referenced by __rbtree_delete_case5().
void __rbtree_destroy_nodes (rbtree_t * t, rbnode_t * n)
Definition at line 654 of file rbtree.c.
References __rbtree_t::free, __rbnode_t::key, __rbnode_t::left, __rbnode_t::right, and __rbnode_t::value.
Referenced by rbtree_destroy().
rbnode_t* __rbtree_grandparent (rbnode_t * n)
Definition at line 61 of file rbtree.c.
References __rbnode_t::parent.
Referenced by __rbtree_insert_case3(), __rbtree_insert_case4(), and __rbtree_insert_case5().
void __rbtree_insert_case1 (rbtree_t * t, rbnode_t * n)
Definition at line 284 of file rbtree.c.
References __rbtree_insert_case2(), BLACK, __rbnode_t::color, and __rbnode_t::parent.
Referenced by __rbtree_insert_case3(), and rbtree_attach_node().
void __rbtree_insert_case2 (rbtree_t * t, rbnode_t * n)
Definition at line 292 of file rbtree.c.
References __rbnode_t_color(), __rbtree_insert_case3(), BLACK, and __rbnode_t::parent.
Referenced by __rbtree_insert_case1().
void __rbtree_insert_case3 (rbtree_t * t, rbnode_t * n)
Definition at line 300 of file rbtree.c.
References __rbnode_t_color(), __rbtree_grandparent(), __rbtree_insert_case1(), __rbtree_insert_case4(), __rbtree_uncle(), BLACK, __rbnode_t::color, __rbnode_t::parent, and RED.
Referenced by __rbtree_insert_case2().
void __rbtree_insert_case4 (rbtree_t * t, rbnode_t * n)
Definition at line 313 of file rbtree.c.
References __rbtree_grandparent(), __rbtree_insert_case5(), __rbtree_rotate_left(), __rbtree_rotate_right(), __rbnode_t::left, __rbnode_t::parent, and __rbnode_t::right.
Referenced by __rbtree_insert_case3().
void __rbtree_insert_case5 (rbtree_t * t, rbnode_t * n)
Definition at line 326 of file rbtree.c.
References __rbtree_grandparent(), __rbtree_rotate_left(), __rbtree_rotate_right(), BLACK, __rbnode_t::color, __rbnode_t::left, __rbnode_t::parent, RED, and __rbnode_t::right.
Referenced by __rbtree_insert_case4().
rbnode_t* __rbtree_maximum_node (rbnode_t * n)
Definition at line 475 of file rbtree.c.
References __rbnode_t::right.
Referenced by rbtree_detach_node().
rbnode_t* __rbtree_new_node (void * key, void * value, enum rbcolor color, rbnode_t * left, rbnode_t * right)
Definition at line 183 of file rbtree.c.
References __rbnode_t::color, __rbnode_t::key, __rbnode_t::left, __rbnode_t::parent, __rbnode_t::right, and __rbnode_t::value.
Referenced by rbtree_insert().
void __rbtree_replace_node (rbtree_t * t, rbnode_t * oldn, rbnode_t * newn)
Definition at line 234 of file rbtree.c.
References __rbnode_t::left, __rbnode_t::parent, __rbnode_t::right, and __rbtree_t::root.
Referenced by __rbtree_rotate_left(), __rbtree_rotate_right(), and rbtree_detach_node().
void __rbtree_rotate_left (rbtree_t * t, rbnode_t * n)
Definition at line 250 of file rbtree.c.
References __rbtree_replace_node(), __rbnode_t::left, __rbnode_t::parent, and __rbnode_t::right.
Referenced by __rbtree_delete_case2(), __rbtree_delete_case5(), __rbtree_delete_case6(), __rbtree_insert_case4(), and __rbtree_insert_case5().
void __rbtree_rotate_right (rbtree_t * t, rbnode_t * n)
Definition at line 264 of file rbtree.c.
References __rbtree_replace_node(), __rbnode_t::left, __rbnode_t::parent, and __rbnode_t::right.
Referenced by __rbtree_delete_case2(), __rbtree_delete_case5(), __rbtree_delete_case6(), __rbtree_insert_case4(), and __rbtree_insert_case5().
rbnode_t* __rbtree_sibling (rbnode_t * n)
Definition at line 69 of file rbtree.c.
References __rbnode_t::left, __rbnode_t::parent, and __rbnode_t::right.
Referenced by __rbtree_delete_case2(), __rbtree_delete_case3(), __rbtree_delete_case4(), __rbtree_delete_case5(), __rbtree_delete_case6(), and __rbtree_uncle().
rbnode_t* __rbtree_uncle (rbnode_t * n)
Definition at line 79 of file rbtree.c.
References __rbtree_sibling(), and __rbnode_t::parent.
Referenced by __rbtree_insert_case3().
int __rbtree_write_gv_node (rbnode_t * n, FILE * fout, int(*)(FILE *fout, void *key) write_node_key, int(*)(FILE *fout, void *value) write_node_value)
Definition at line 714 of file rbtree.c.
References __rbnode_t::color, __rbnode_t::key, __rbnode_t::left, __rbnode_t::parent, RED, __rbnode_t::right, and __rbnode_t::value.
Referenced by rbtree_write_gv().
rbnode_t* rbtree_apply (rbtree_t * t, rbtree_func func)
Apply a transformation to each value of each node in the tree.
Return value:
Success: NULL
Failure: rbnode_t * pointer to the node on which func() failed
See also:
rbtree_func()
Example: The following code demonstrates how to create and use an apply function that will be called on all key/value pairs in a tree.
rbnode_t * n = NULL;
n = rbtree_apply(t, apply);
// On failure, n will point to the node on which the apply function failed
// On success, n will be NULL
assert(n == NULL);
Definition at line 705 of file rbtree.c.
References __rbtree_apply_function(), and __rbtree_t::root.
Referenced by test_009().
rbnode_t* rbtree_attach_node (rbtree_t * t, rbnode_t * n)
Attach a node to the tree.
Return value:
Success: rbtree_t * pointer to the newly attached node
Failure: NULL
Notes: Be aware that the rbnode_t * pointer passed back may have a different address than the pointer passed in. Therefore proper usage should be:
n = rbtree_attach_node(t, n);
if (n == NULL) {
        printf("Attach failed\n");
}
Notes: Be aware that when inserting a node with a duplicate key, the original node's key/value pair are removed and replaced with the new key/value pair.
Definition at line 403 of file rbtree.c.
References __rbtree_insert_case1(), __rbtree_verify_properties, __rbnode_t::color, __rbtree_t::compare, __rbtree_t::free, __rbnode_t::key, __rbnode_t::left, __rbnode_t::parent, RED, __rbnode_t::right, __rbtree_t::root, __rbtree_t::size, and __rbnode_t::value.
Referenced by rbtree_insert().
int rbtree_clear (rbtree_t * t)
Empty the tree by destroying all of it's nodes.
Notes: The key/value pairs stored in the nodes are not destroyed.
Return value:
Success: 1
Failure: 0
if (!rbtree_clear(t)) {
        printf("Failed\n");
}
Definition at line 167 of file rbtree.c.
References __rbnode_t::parent, rbtree_post_order_first(), rbtree_post_order_next(), and rbtree_remove().
Referenced by test_010().
rbtree_t* rbtree_clone (rbtree_t * t)
Make a copy of a tree.
Return value:
Success: rbtree_t * pointer to the cloned tree
Failure: NULL
Notes: Be aware that cloning a tree merely copies the key and value pointers. It does not create copies of what they key and value pointers point to.
Example:
rbtree_t * t2 = rbtree_clone(t);
Definition at line 689 of file rbtree.c.
References __rbtree_clone_node(), __rbtree_t::compare, __rbtree_t::free, rbtree_create(), rbtree_destroy(), and rbtree_top().
Referenced by test_004(), and test_delete_permutation().
rbtree_t* rbtree_create (rbtree_compare compare, rbtree_free free)
Create a new tree.
Compare is a pointer to a function used to compare void keys. Compare cannot be NULL. Free is a pointer to a function to call when destroying nodes. Free is responsible for properly releasing any memory used for the key and value stored by the node.
Return value:
Success: A rbtree * pointer
Failure: NULL
See also:
rbtree_compare()
rbtree_free()
Example:
rbtree_t * t = rbtree_create(rbnode_data_cmp, NULL);
assert(t != NULL);
// ... stuff ...
t = rbtree_destroy(t); // t will be set to NULL on success
Definition at line 153 of file rbtree.c.
References __rbtree_verify_properties, compare(), __rbtree_t::compare, __rbtree_t::free, __rbtree_t::root, and __rbtree_t::size.
Referenced by mf__mem_init(), rbtree_clone(), test_001(), test_002(), test_003(), test_004(), test_005(), test_006(), test_007(), test_008(), test_009(), and test_010().
rbtree_t* rbtree_destroy (rbtree_t * t)
Destroy a tree and free all nodes, keys, and values.
Return value: NULL
Example:
rbtree_t * t = rbtree_create(cmp, NULL);
// ... stuff ...
t = rbtree_destroy(t);
Definition at line 665 of file rbtree.c.
References __rbtree_destroy_nodes(), and __rbtree_t::root.
Referenced by rbtree_clone(), test_001(), test_002(), test_003(), test_004(), test_005(), test_006(), test_007(), test_008(), test_009(), test_010(), and test_delete_permutation().
rbnode_t* rbtree_detach_node (rbtree_t * t, rbnode_t * n)
Detach the given node from the tree.
Return value:
Success: rbnode_t * pointer to the new detached node
Failure: NULL
Notes: Be aware that the rbnode_t * pointer passed back may have a different address than the pointer passed in. Therefore proper usage should be:
n = rbtree_detach_node(t, n);
if (n == NULL) {
        printf("Detach failed\n");
}
Definition at line 587 of file rbtree.c.
References __rbnode_t_color(), __rbtree_delete_case1(), __rbtree_maximum_node(), __rbtree_replace_node(), __rbtree_verify_properties, BLACK, __rbnode_t::color, __rbnode_t::key, __rbnode_t::left, __rbnode_t::parent, RED, __rbnode_t::right, __rbtree_t::size, and __rbnode_t::value.
Referenced by rbtree_remove().
rbnode_t* rbtree_find (rbtree_t * t, void * key)
Given a tree and a key, search the tree for a node with the given key.
Return value:
Success: rbnode_t *
Failure: NULL
Example:
rbnode_t * n = rbtree_find(t, (void *)&key);
if (n == NULL) {
        printf("Not found\n");
}
else {
        printf("Found: key = %d, value = %d\n", *(int *)rbtree_key(n), *(int *)rbtree_value(n));
}
Definition at line 204 of file rbtree.c.
References __rbtree_t::compare, __rbnode_t::key, __rbnode_t::left, __rbnode_t::right, and __rbtree_t::root.
Referenced by mf__mem_end(), mf__mem_free(), mf__mem_size(), test_002(), test_004(), test_delete_permutation(), test_insert_permutation(), and test_tree().
rbnode_t* rbtree_in_order_first (rbtree_t * t)
Given a tree, return the first node for in-order traversal.
Return value:
Success: rbnode_t *
Failure: NULL – The tree is empty
TODO: Write an example for this
Definition at line 824 of file rbtree.c.
References __rbnode_t::left, and __rbtree_t::root.
Referenced by rbtrees_are_identical(), test_002(), test_006(), test_008(), test_in_order_traversal(), and test_tree().
rbnode_t* rbtree_in_order_last (rbtree_t * t)
Given a tree, return the first node for reverse in-order traversal.
Return value:
Success: rbnode_t *
Failure: NULL – The tree is empty
TODO: Write an example for this
Definition at line 839 of file rbtree.c.
References __rbnode_t::right, and __rbtree_t::root.
Referenced by test_006(), and test_in_order_traversal().
rbnode_t* rbtree_in_order_next (rbnode_t * n)
Given a node, return the next node via in-order traversal.
Return value:
Success: rbnode_t *
Failure: NULL – There is no next node
TODO: Write an example for this
Definition at line 854 of file rbtree.c.
References __rbnode_t::left, __rbnode_t::parent, and __rbnode_t::right.
Referenced by rbtree_level_order_next(), rbtrees_are_identical(), test_002(), test_006(), test_008(), test_in_order_traversal(), and test_tree().
rbnode_t* rbtree_in_order_prev (rbnode_t * n)
Given a node, return the previous node via reverse in-order traversal.
Return value:
Success: rbnode_t *
Failure: NULL – There is no previous node
TODO: Write an example for this
Definition at line 882 of file rbtree.c.
References __rbnode_t::left, __rbnode_t::parent, and __rbnode_t::right.
Referenced by rbtree_level_order_prev(), test_006(), and test_in_order_traversal().
int rbtree_insert (rbtree_t * t, void * key, void * value)
Create a new node with the given key/value pair, and insert it into the tree.
Return value:
Success: 1
Failure: 0
Notes: Be aware that when inserting a duplicate key, the original node is removed and replaced with the new key/value pair.
int * key = malloc(sizeof(int));
int * value = malloc(sizeof(int));
*key = 5;
*value = 7;
if (!rbtree_insert(t, (void *)key, (void *)value)) {
        printf("Failed\n");
}
Definition at line 460 of file rbtree.c.
References __rbtree_new_node(), rbtree_attach_node(), and RED.
Referenced by __rbtree_clone_node(), mf__mem_alloc(), mf__mem_realloc(), test_002(), test_004(), test_005(), test_006(), test_007(), test_008(), test_009(), test_010(), and test_insert_permutation().
void* rbtree_key (rbnode_t * n)
Return the key from a node.
TODO: Write an example for this
Definition at line 794 of file rbtree.c.
References __rbnode_t::key.
Referenced by __rbtree_clone_node(), mf__mem_begin(), test_002(), test_008(), test_in_order_traversal(), and test_tree().
rbnode_t* rbtree_left (rbnode_t * n)
Return the left child of a node.
Return value:
Success: rbnode_t *
Failure: NULL – The node has no left child
TODO: Write an example for this
Definition at line 809 of file rbtree.c.
References __rbnode_t::left.
Referenced by __rbtree_clone_node(), and mf__mem_begin().
rbnode_t* rbtree_level_order_first (rbtree_t * t)
Given a tree, return the first node for level-order traversal.
Return value:
Success: rbnode_t *
Failure: NULL – The tree is empty
TODO: Write an example for this
Definition at line 1083 of file rbtree.c.
References __rbtree_t::root.
Referenced by test_006().
rbnode_t* rbtree_level_order_last (rbtree_t * t)
Given a tree, return the first node for reverse level-order traversal.
Return value:
Success: rbnode_t *
Failure: NULL – The tree is empty
TODO: Write an example for this
Definition at line 1101 of file rbtree.c.
References __rbnode_t_depth(), rbtree_post_order_last(), rbtree_post_order_prev(), and rbtree_top().
Referenced by test_006().
rbnode_t* rbtree_level_order_next (rbnode_t * n)
Given a node, return the next node via level-order traversal.
Return value:
Success: rbnode_t *
Failure: NULL – There is no next node
TODO: Write an example for this
Definition at line 1125 of file rbtree.c.
References __rbnode_t_depth(), __rbnode_t::left, __rbnode_t::parent, rbtree_in_order_next(), and rbtree_post_order_next().
Referenced by test_006().
rbnode_t* rbtree_level_order_prev (rbnode_t * n)
Given a node, return the previous node via reverse level-order traversal.
Return value:
Success: rbnode_t *
Failure: NULL – There is no previous node
TODO: Write an example for this
Definition at line 1155 of file rbtree.c.
References __rbnode_t_depth(), __rbnode_t::parent, rbtree_in_order_prev(), rbtree_post_order_prev(), and __rbnode_t::right.
Referenced by test_006().
rbnode_t* rbtree_parent (rbnode_t * n)
Return the parent node of a node.
Return value:
Success: rbnode_t *
Failure: NULL – The node has no parent
TODO: Write an example for this
Definition at line 819 of file rbtree.c.
References __rbnode_t::parent.
Referenced by __rbnode_t_depth().
rbnode_t* rbtree_post_order_first (rbtree_t * t)
Given a tree, return the first node for post-order traversal.
Return value:
Success: rbnode_t *
Failure: NULL – The tree is empty
TODO: Write an example for this
Definition at line 983 of file rbtree.c.
References __rbnode_t::left, and __rbtree_t::root.
Referenced by rbtree_clear(), and test_002().
rbnode_t* rbtree_post_order_last (rbtree_t * t)
Given a tree, return the first node for reverse post-order traversal.
Return value:
Success: rbnode_t *
Failure: NULL – The tree is empty
TODO: Write an example for this
Definition at line 998 of file rbtree.c.
References __rbtree_t::root.
Referenced by rbtree_level_order_last().
rbnode_t* rbtree_post_order_next (rbnode_t * n)
Given a node, return the next node via post-order traversal.
Return value:
Success: rbnode_t *
Failure: NULL – There is no next node
TODO: Write an example for this
Definition at line 1005 of file rbtree.c.
References __rbnode_t::left, __rbnode_t::parent, and __rbnode_t::right.
Referenced by rbtree_clear(), rbtree_level_order_next(), and test_002().
rbnode_t* rbtree_post_order_prev (rbnode_t * n)
Given a node, return the previous node via reverse post-order traversal.
Return value:
Success: rbnode_t *
Failure: NULL – There is no previous node
TODO: Write an example for this
Definition at line 1026 of file rbtree.c.
References __rbnode_t::left, __rbnode_t::parent, and __rbnode_t::right.
Referenced by rbtree_level_order_last(), and rbtree_level_order_prev().
rbnode_t* rbtree_pre_order_first (rbtree_t * t)
Given a tree, return the first node for pre-order traversal.
Return value:
Success: rbnode_t *
Failure: NULL – The tree is empty
TODO: Write an example for this
Definition at line 910 of file rbtree.c.
References __rbtree_t::root.
Referenced by test_002().
rbnode_t* rbtree_pre_order_last (rbtree_t * t)
Given a tree, return the first node for reverse pre-order traversal.
Return value:
Success: rbnode_t *
Failure: NULL – The tree is empty
TODO: Write an example for this
Definition at line 919 of file rbtree.c.
References __rbnode_t::right, and __rbtree_t::root.
rbnode_t* rbtree_pre_order_next (rbnode_t * n)
Given a node, return the next node via pre-order traversal.
Return value:
Success: rbnode_t *
Failure: NULL – There is no next node
TODO: Write an example for this
Definition at line 933 of file rbtree.c.
References __rbnode_t::left, __rbnode_t::parent, and __rbnode_t::right.
Referenced by test_002().
rbnode_t* rbtree_pre_order_prev (rbnode_t * n)
Given a node, return the previous node via reverse in-order traversal.
Return value:
Success: rbnode_t *
Failure: NULL – There is no previous node
TODO: Write an example for this
Definition at line 961 of file rbtree.c.
References __rbnode_t::left, __rbnode_t::parent, and __rbnode_t::right.
int rbtree_remove (rbtree_t * t, rbnode_t * n)
Given a tree and a node, remove the node from the tree.
Return value:
Success: 1
Failure: 0
Example:
rbnode_t * n = rbtree_find(t, k);
if (n != NULL) {
        printf("Found it\n");
        printf("Key: %s\n", (char *)rbtree_key(n));
        printf("Value: %d\n", *(int *)rbtree_value(n));
} else {
        printf("Not found\n");
}
Definition at line 622 of file rbtree.c.
References __rbtree_t::free, __rbnode_t::key, rbtree_detach_node(), and __rbnode_t::value.
Referenced by mf__mem_free(), rbtree_clear(), test_004(), test_delete_permutation(), and test_insert_permutation().
rbnode_t* rbtree_right (rbnode_t * n)
Return the right child of a node.
Return value:
Success: rbnode_t *
Failure: NULL – The node has no right child
TODO: Write an example for this
Definition at line 814 of file rbtree.c.
References __rbnode_t::right.
Referenced by __rbtree_clone_node(), and mf__mem_begin().
size_t rbtree_size (rbtree_t * t)
Return the number of nodes in the tree.
Example:
size_t num_elements = rbtree_size(t);
Definition at line 632 of file rbtree.c.
References __rbtree_t::size.
Referenced by test_001(), test_002(), test_007(), and test_010().
rbnode_t* rbtree_top (rbtree_t * t)
Return the root node of a tree.
Return value:
Success: rbnode_t *
Failure: NULL – The tree is empty
TODO: Write an example for this
Definition at line 804 of file rbtree.c.
References __rbtree_t::root.
Referenced by mf__mem_begin(), rbtree_clone(), rbtree_level_order_last(), test_001(), and test_002().
void* rbtree_value (rbnode_t * n)
Return the value from a node.
TODO: Write an example for this
Definition at line 799 of file rbtree.c.
References __rbnode_t::value.
Referenced by __rbtree_clone_node(), mf__mem_begin(), mf__mem_end(), mf__mem_size(), test_006(), test_008(), test_in_order_traversal(), and test_tree().
int rbtree_write_gv (rbtree_t * t, char * filename, int(*)(FILE *fout, void *key) write_node_key, int(*)(FILE *fout, void *value) write_node_value)
Write a tree as a graphviz dot file.
Return value:
Success: 1
Failure: 0
TODO: Write an example for this
Definition at line 765 of file rbtree.c.
References __rbtree_write_gv_node(), and __rbtree_t::root.
int rbtrees_are_identical (rbtree_t * t1, rbtree_t * t2)
Determine if two trees are identical.
Return value:
Success: 1 – Trees are identical
Failure: 0 – Trees differ
Example:
if (rbtrees_are_identical(t1, t2)) {
        printf("Identical\n");
}
else {
        printf("Differ\n");
}
Definition at line 1054 of file rbtree.c.
References __rbtree_t::compare, rbtree_in_order_first(), rbtree_in_order_next(), __rbtree_t::size, and __rbnode_t::value.
Referenced by test_004().