cgdsa-c: str.c File Reference
str.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "mem.h"
#include "dllist.h"
Functions
char * str_reserve (char *str, size_t size)
Increase the capacity of a string to at least size bytes.
size_t str_len (char *str)
Return the length of the string.
char * str_create (char *src)
Create a new string.
char * str_destroy (char *str)
Destroy a string, freeing it's memory.
size_t str_capacity (char *str)
Return the number of bytes that the string can hold, including the terminating '\0'.
char * str_shrink_reserve (char *str)
Shrink a string's capacity.
void str_clear (char *str)
Clear the contents of a string.
char * str_assign (char *dst, char *src)
Assign a value to a string.
char * str_insert (char *dst, char *src)
Insert one string into another.
char * str_erase (char *str, size_t len)
Erase characters from a string.
char * str_replace (char *dst, size_t len, char *src)
Replace characters in one string with the contents of another.
char * str_find (char *haystack, char *needle)
Perform a forward search for string needle in string haystack.
char * str_caseless_find (char *haystack, char *needle)
Perform a forward search for string needle in string haystack, ignore case.
char * str_rfind (char *haystack, char *needle)
Perform a reverse search for string needle in string haystack.
char * str_caseless_rfind (char *haystack, char *needle)
Perform a reverse search for string needle in string haystack, ignore case.
char * str_find_char (char *haystack, char *needles)
Perform a forward search of haystack for any character in needles.
char * str_rfind_char (char *haystack, char *needles)
Perform a reverse search of haystack for any chacter in needles.
char * str_find_not_char (char *haystack, char *needles)
Perform a forward search of haystack for any character not in needles.
char * str_rfind_not_char (char *haystack, char *needles)
Perform a forward search of haystack for any character not in needles.
char * str_substr (char *src, size_t len)
Create and return a new string containing a substring of src.
int str_compare (char *str1, char *str2)
Compare two strings.
int str_caseless_compare (char *str1, char *str2)
Compare two strings, ignore case.
int str_swap (char **str1, char **str2)
Swap the contents of two strings.
char * str_append (char *dst, char *src)
Append one string to the end of another.
char * str_prepend (char *dst, char *src)
Prepend one string to the beginning of another.
size_t str_getline (char **str, FILE *fin, char *delimiters)
Read input from a stream into a string.
dllist_t * str_split (char *src, char *delimiters, size_t max_split)
Split a string into a list.
char * str_join (dllist_t *list, char *separator)
Join a list of strings together.
Function Documentation
char* str_append (char * dst, char * src)
Append one string to the end of another.
Arguments:
char * dst – A pointer to a location within a string
char * src – A pointer to a location within a string
Return value:
Success: char * – A pointer to the head of dst
Failure: NULL
Definition at line 374 of file str.c.
References mem_begin(), str_insert(), and str_len().
Referenced by main(), str_getline(), and str_join().
char* str_assign (char * dst, char * src)
Assign a value to a string.
Arguments:
char * dst – A pointer to a location within the destination string
char * src – A pointer to a location within the source string
Return value:
Success: char * – A pointer to the head of dst (whose memory location may have changed due to (re)allocation)
Failure: NULL
NOTES:
If src is NULL, the procedure fails and NULL is returned.
If dst is NULL, dst will be allocated.
If dst is a location within a string, then the rest of the string is truncated at dst, and replaced with the contents of src.
Uses memmove(), so src and dst may overlap.
Definition at line 113 of file str.c.
References mem_begin(), str_len(), and str_reserve().
Referenced by main(), and str_swap().
size_t str_capacity (char * str)
Return the number of bytes that the string can hold, including the terminating '\0'.
Arguments:
char * str – A pointer to a location within a string
Return value:
Success: size_t number of bytes
Failure: 0
NOTES:
Only use str_capacity() on strings created with str_*() routines.
Whether or not str is the head of the string or a location within the string makes no difference.
Definition at line 90 of file str.c.
References mem_size().
Referenced by main().
int str_caseless_compare (char * str1, char * str2)
Compare two strings, ignore case.
Arguments:
char * str1 – A pointer to a location within a string
char * str2 – A pointer to a location within a string
Return value:
int < 0 – str1 < str2
int == 0 – str1 == str2
int > 0 – str1 > str2
NOTES:
Mixing str_*() functions with string functions from the standard C library may cause memory leaks and seg-faults. This is why it is encouraged that the user not intermix the use of str_*() functions with string functions from the standard C library. This function is supplied as a convenience wrapper for strcasecmp.
Definition at line 357 of file str.c.
Referenced by main().
char* str_caseless_find (char * haystack, char * needle)
Perform a forward search for string needle in string haystack, ignore case.
Arguments:
char * haystack – A pointer to a location within a string
char * needle – A pointer to a search string
Return value:
Success: char * – A pointer to the first occurence of needle in haystack
Failure: NULL
Definition at line 206 of file str.c.
References str_len().
Referenced by main().
char* str_caseless_rfind (char * haystack, char * needle)
Perform a reverse search for string needle in string haystack, ignore case.
Arguments:
char * haystack – A pointer to a location within a string
char * needle – A pointer to a search string
Return value:
Success: char * – A pointer to the last occurence of needle in haystack
Failure: NULL
Definition at line 246 of file str.c.
References mem_begin(), and str_len().
Referenced by main().
void str_clear (char * src)
Clear the contents of a string.
Arguments:
char * str – A pointer to a location within a string.
Return value: none
NOTES:
If str is a location within a string, then the string is truncated at that location.
Definition at line 107 of file str.c.
Referenced by main().
int str_compare (char * str1, char * str2)
Compare two strings.
Arguments:
char * str1 – A pointer to a location within a string
char * str2 – A pointer to a location within a string
Return value:
int < 0 – str1 < str2
int == 0 – str1 == str2
int > 0 – str1 > str2
NOTES:
Mixing str_*() functions with string functions from the standard C library may cause memory leaks and seg-faults. This is why it is encouraged that the user not intermix the use of str_*() functions with string functions from the standard C library. This function is supplied as a convenience wrapper for strcasecmp.
Definition at line 351 of file str.c.
Referenced by main().
char* str_create (char * src)
Create a new string.
Arguments:
char * src – A pointer to a string to use for initialization. The contents of src will be copied into the newly-created string. If src is a pointer to a location within a string, then only the remaining characters starting at src will be copied. If src is NULL, then the newly-created string is initialized to "\0".
Returns:
Success: char * pointer to the new string
Failure: NULL
NOTES:
Calls str_reserve() for memory allocation, see notes for str_reserve()
The contents of src are copied into the newly-created string.
If src is a pointer to a location within a string, then only the remaining characters from src to the end of the string are copied.
If src is NULL, then the newly-created string is initialized to "\0".
Definition at line 65 of file str.c.
References str_len(), and str_reserve().
Referenced by main(), str_insert(), str_join(), str_shrink_reserve(), str_split(), str_substr(), and str_swap().
char* str_destroy (char * str)
Destroy a string, freeing it's memory.
Arguments:
char * str – A pointer to the string, or a location within a string.
Returns: char * – NULL
NOTES:
Only use str_destroy() on strings created with str_*() routines.
If str is NULL then there is no effect.
If str is a pointer to a location within the string, then the head of the string is found first so that the entire string can be destroyed.
Definition at line 84 of file str.c.
References mem_free().
Referenced by main(), and str_shrink_reserve().
char* str_erase (char * str, size_t len)
Erase characters from a string.
Arguments:
char * str – A pointer to a location within a string
size_t len – The number of characters to remove
Return value:
Success: char * – A pointer to the head of str
Failure: NULL
Definition at line 161 of file str.c.
References mem_begin(), and str_len().
Referenced by main(), and str_replace().
char* str_find (char * haystack, char * needle)
Perform a forward search for string needle in string haystack.
Arguments:
char * haystack – A pointer to a location within a string
char * needle – A pointer to a search string
Return value:
Success: char * – A pointer to the first occurence of needle in haystack
Failure: NULL
Definition at line 187 of file str.c.
References str_len().
Referenced by main().
char* str_find_char (char * haystack, char * needles)
Perform a forward search of haystack for any character in needles.
Arguments:
char * haystack – A pointer to a location within a string
char * needles – A pointer to a string of characters
Return value:
Success: char * – A pointer to the first character in haystack that is also found in needles found. Search begins at haystack, and the return value is a pointer location greater than or equal to haystack.
Failure: NULL
Definition at line 264 of file str.c.
References str_len().
Referenced by main(), and str_split().
char* str_find_not_char (char * haystack, char * needles)
Perform a forward search of haystack for any character not in needles.
Arguments:
char * haystack – A pointer to a location within a string
char * needles – A pointer to a sting of characters
Return value:
Success: char * – A pointer to the first character in haystack that is not found in needles. Search begins at haystack, and the return value is a pointer location greater than or equal to haystack.
Failure: NULL
Definition at line 301 of file str.c.
References str_len().
Referenced by main(), and str_split().
size_t str_getline (char ** str, FILE * fin, char * delimiters)
Read input from a stream into a string.
Arguments:
char ** str – A pointer to a char *
FILE * fin – A pointer to a file stream
char * delimiters – A pointer to a string of delimiter characters
Return value:
Success: size_t – The number of characters read in from fin
Failure: 0
Definition at line 394 of file str.c.
References str_append().
Referenced by main().
char* str_insert (char * dst, char * src)
Insert one string into another.
Arguments:
char * dst – A pointer to a location within the destination string
char * src – A pointer to a location within the source string
Return value:
Success: char * – A pointer to the head of dst (whose memory location may have changed due to (re)allocation)
Failure: NULL
NOTES:
If src is NULL, the procedure fails and NULL is returned.
If dst is NULL, dst will be allocated.
If dst is a location within a string, then insertion will begin at dst
If src is a location within a string, then only the characters from src to the end of src will be inserted
Uses memmove(), so src and dst may overlap.
Definition at line 130 of file str.c.
References mem_begin(), str_create(), str_len(), and str_reserve().
Referenced by main(), str_append(), str_prepend(), and str_replace().
char* str_join (dllist_t * list, char * separator)
Join a list of strings together.
Arguments:
dllist_t * list – A pointer to a list of strings
char * separator – A string of characters to use as separators between each string in the list
Return value:
Success: char * – A pointer to a new string
Failure: NULL
NOTES:
The newly-constructed string is a copy. This means that it is safe to alter or destroy the list and the separator without harming the returned sring.
Definition at line 472 of file str.c.
References dllist_first(), dllist_next(), dllist_value(), str_append(), and str_create().
Referenced by main().
size_t str_len (char * str)
Return the length of the string.
Arguments:
char * str – A pointer to a location within a string
Return value:
Success: size_t number of characters in the string, excluding the terminating '\0'.
Failure: 0
NOTES:
If str is not the head of the string, then only the remaining characters between str and the end of the string will be counted.
Definition at line 59 of file str.c.
Referenced by main(), str_append(), str_assign(), str_caseless_find(), str_caseless_rfind(), str_create(), str_erase(), str_find(), str_find_char(), str_find_not_char(), str_insert(), and str_rfind().
char* str_prepend (char * dst, char * src)
Prepend one string to the beginning of another.
Arguments:
char * dst – A pointer to a location within a string
char * src – A pointer to a location within a string
Return value:
Success: char * – A pointer to the head of dst
Failure: NULL
Definition at line 385 of file str.c.
References mem_begin(), and str_insert().
Referenced by main().
char* str_replace (char * dst, size_t len, char * src)
Replace characters in one string with the contents of another.
Arguments:
char * dst – A pointer to a location within the destination string
size_t len – The number of characters in dst to replace
char * src – A pointer to a location within the source string
Return value:
char * – A pointer to the head of dst
Definition at line 172 of file str.c.
References mem_begin(), str_erase(), and str_insert().
Referenced by main().
char* str_reserve (char * str, size_t size)
Increase the capacity of a string to at least size bytes.
Arguments:
char * str – A pointer to a location within a string
size_t size – The number of bytes to reserve
Return value:
Success: char * – A pointer to the head of the string (whose memory location may have changed during memory reallocation)
Failure: NULL
NOTES:
Only use str_reserve() for strings created with the str_*() routines.
Whether or not str is the head of the string or a location within the string makes no difference.
Memory (re)allocation for strings follows an exponential allocation strategy. This is a trade-off between memory usage and speed. Each time the string asks for an increased reserve, the amount of memory allocated doubles.
Definition at line 41 of file str.c.
References mem_begin(), mem_end(), and mem_realloc().
Referenced by main(), str_assign(), str_create(), str_insert(), and str_substr().
char* str_rfind (char * haystack, char * needle)
Perform a reverse search for string needle in string haystack.
Arguments:
char * haystack – A pointer to a location within a string
char * needle – A pointer to a search string
Return value:
Success: char * – A pointer to the last occurence of needle in haystack
Failure: NULL
Definition at line 225 of file str.c.
References mem_begin(), and str_len().
Referenced by main().
char* str_rfind_char (char * haystack, char * needles)
Perform a reverse search of haystack for any chacter in needles.
Arguments:
char * haystack – A pointer to a location within a string
char * needles – A pointer to a sting of characters
Return value:
Success: char * – A pointer to the first character found in haystack that is also in needles. Search begins at haystack, and the return value is a pointer location less than or equal to haystack.
Failure: NULL
Definition at line 283 of file str.c.
References mem_begin().
Referenced by main().
char* str_rfind_not_char (char * heystack, char * needles)
Perform a forward search of haystack for any character not in needles.
Arguments:
char * haystack – A pointer to a location within a string
char * needles – A pointer to a sting of characters
Return value:
Success: char * – A pointer to the first character in haystack that is not found in needles. Search begins at haystack, and the return value is a pointer location greater than or equal to haystack.
Failure: NULL
Definition at line 320 of file str.c.
References mem_begin().
Referenced by main().
char* str_shrink_reserve (char * str)
Shrink a string's capacity.
Arguments:
char * str – A pointer to a location within a string.
Return value:
Success: char * pointer to the head of the string (whose memory location may have changed during memory reallocation)
Failure: NULL
NOTES:
Only use str_reserve() for strings created with the str_*() routines.
Whether or not str is the head of the string or a location within the string makes no difference.
Calls str_create(), see notes for str_create().
Definition at line 95 of file str.c.
References mem_begin(), str_create(), and str_destroy().
Referenced by main().
dllist_t* str_split (char * src, char * delimiters, size_t max_split)
Split a string into a list.
Arguments:
char * src – A pointer to a location within a source string
char * delimiters – A list of delimiter characters
size_t max_split – The maximum number of splits to make
Return value:
Success: dllist_t * – A pointer to a list containing new strings
Failure: NULL
NOTES:
Substrings split from src are copied. This means that it is safe to alter or destroy src without changing the contents of the list.
If the number of splits possible are greater than max_split, then the last string in the list will contain the remainder of the line.
Definition at line 412 of file str.c.
References dllist_create(), dllist_destroy(), dllist_free_node(), dllist_push_back(), str_create(), str_find_char(), str_find_not_char(), and str_substr().
Referenced by main().
char* str_substr (char * src, size_t len)
Create and return a new string containing a substring of src.
Arguments:
char * src – A pointer to a location within a string
size_t len – The number of characters in substr.
Return value:
Success: char * – A pointer to a newly-created string.
Failure: NULL
Definition at line 338 of file str.c.
References str_create(), and str_reserve().
Referenced by main(), and str_split().
int str_swap (char ** str1, char ** str2)
Swap the contents of two strings.
Arguments:
char ** str1 – A pointer to a char *
char ** str2 – A pointer to a char *
Return value:
Success: 1
Failure: 0
Definition at line 363 of file str.c.
References str_assign(), and str_create().
Referenced by main().