cgdsa-c: test-mem.c File Reference
test-mem.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include "mem.h"
Functions
void test_001 (void)
void test_002 (void)
void test_003 (void)
void test_004 (void)
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Definition at line 76 of file test-mem.c.
References test_001(), test_002(), test_003(), and test_004().
void test_001 (void)
Definition at line 7 of file test-mem.c.
References mem_alloc(), mem_end(), mem_free(), and mem_size().
Referenced by main().
void test_002 (void)
Definition at line 22 of file test-mem.c.
References mem_alloc(), mem_end(), mem_free(), mem_realloc(), and mem_size().
Referenced by main().
void test_003 (void)
Definition at line 43 of file test-mem.c.
References mem_alloc(), mem_end(), mem_free(), and mem_size().
Referenced by main().
void test_004 (void)
Definition at line 62 of file test-mem.c.
References mem_alloc(), mem_begin(), and mem_free().
Referenced by main().