cgdsa-c: test-mem-pthread.c File Reference
test-mem-pthread.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <pthread.h>
#include <unistd.h>
#include "mem.h"
Macros
#define NUM_THREADS 8
#define NUM_REPETITIONS 100000
Functions
void test_001 (void)
void test_002 (void)
void test_003 (void)
void test_004 (void)
void * thread_func (void *idptr)
int main (int argc, char **argv)
Variables
int go_flag = 0
Macro Definition Documentation
#define NUM_REPETITIONS 100000
Definition at line 8 of file test-mem-pthread.c.
Referenced by thread_func().
#define NUM_THREADS 8
Definition at line 7 of file test-mem-pthread.c.
Referenced by main().
Function Documentation
int main (int argc, char ** argv)
Definition at line 101 of file test-mem-pthread.c.
References go_flag, NUM_THREADS, and thread_func().
void test_001 (void)
Definition at line 14 of file test-mem-pthread.c.
References mem_alloc(), mem_end(), mem_free(), and mem_size().
Referenced by thread_func().
void test_002 (void)
Definition at line 29 of file test-mem-pthread.c.
References mem_alloc(), mem_end(), mem_free(), mem_realloc(), and mem_size().
Referenced by thread_func().
void test_003 (void)
Definition at line 50 of file test-mem-pthread.c.
References mem_alloc(), mem_end(), mem_free(), and mem_size().
Referenced by thread_func().
void test_004 (void)
Definition at line 73 of file test-mem-pthread.c.
References mem_alloc(), mem_begin(), and mem_free().
Referenced by thread_func().
void* thread_func (void * idptr)
Definition at line 87 of file test-mem-pthread.c.
References go_flag, NUM_REPETITIONS, test_001(), test_002(), test_003(), and test_004().
Referenced by main().
Variable Documentation
int go_flag = 0
Definition at line 12 of file test-mem-pthread.c.
Referenced by main(), and thread_func().