cgdsa-c: test-rbtree.c File Reference
test-rbtree.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <string.h>
#include "rbtree.h"
Macros
#define DEBUG
Functions
int write_key (FILE *fout, void *key)
int cmp (const void *left, const void *right)
void test_001 (void)
void test_002 (void)
int compare (const void *a1, const void *a2)
void test_tree (rbtree_t *t, int s, int k[], double d[], unsigned long long b)
void test_delete_permutation (rbtree_t *t, int s, int *k, double *d, int index, unsigned long long b)
void test_insert_permutation (rbtree_t *t, int s, int *k, double *d, int index, int bits_left, unsigned long long b)
void test_003 (void)
int __write_node_key (FILE *fout, void *key)
int __write_node_value_char (FILE *fout, void *value)
int __write_node_value_double (FILE *fout, void *value)
void test_in_order_traversal (rbtree_t *t)
void test_004 (void)
void test_005 (void)
void test_006 (void)
void test_007 (void)
void test_008 (void)
int main (int argc, char **argv)
Macro Definition Documentation
#define DEBUG
Definition at line 8 of file test-rbtree.c.
Function Documentation
int __write_node_key (FILE * fout, void * key)
Definition at line 313 of file test-rbtree.c.
int __write_node_value_char (FILE * fout, void * value)
Definition at line 322 of file test-rbtree.c.
int __write_node_value_double (FILE * fout, void * value)
Definition at line 330 of file test-rbtree.c.
int cmp (const void * left, const void * right)
Definition at line 69 of file test-rbtree.c.
Referenced by test_001(), and test_002().
int compare (const void * a1, const void * a2)
Definition at line 162 of file test-rbtree.c.
Referenced by test_003(), test_004(), test_005(), test_006(), test_007(), and test_008().
int main (int argc, char ** argv)
Definition at line 1107 of file test-rbtree.c.
References test_001(), test_002(), test_003(), test_004(), test_005(), test_006(), test_007(), and test_008().
void test_001 (void)
Definition at line 81 of file test-rbtree.c.
References cmp(), rbtree_create(), rbtree_destroy(), rbtree_size(), and rbtree_top().
Referenced by main().
void test_002 (void)
Definition at line 93 of file test-rbtree.c.
References cmp(), rbtree_create(), rbtree_destroy(), rbtree_find(), rbtree_in_order_first(), rbtree_in_order_next(), rbtree_insert(), rbtree_key(), rbtree_post_order_first(), rbtree_post_order_next(), rbtree_pre_order_first(), rbtree_pre_order_next(), rbtree_size(), and rbtree_top().
Referenced by main().
void test_003 (void)
Definition at line 280 of file test-rbtree.c.
References compare(), rbtree_create(), rbtree_destroy(), and test_insert_permutation().
Referenced by main().
void test_004 (void)
Definition at line 370 of file test-rbtree.c.
References compare(), rbtree_clone(), rbtree_create(), rbtree_destroy(), rbtree_find(), rbtree_insert(), rbtree_remove(), rbtrees_are_identical(), and test_in_order_traversal().
Referenced by main().
void test_005 (void)
Definition at line 421 of file test-rbtree.c.
References compare(), rbtree_create(), rbtree_destroy(), rbtree_insert(), and test_in_order_traversal().
Referenced by main().
void test_006 (void)
Definition at line 491 of file test-rbtree.c.
References compare(), rbtree_create(), rbtree_destroy(), rbtree_in_order_first(), rbtree_in_order_last(), rbtree_in_order_next(), rbtree_in_order_prev(), rbtree_insert(), rbtree_level_order_first(), rbtree_level_order_last(), rbtree_level_order_next(), rbtree_level_order_prev(), and rbtree_value().
Referenced by main().
void test_007 (void)
Definition at line 840 of file test-rbtree.c.
References compare(), rbtree_create(), rbtree_destroy(), rbtree_insert(), and rbtree_size().
Referenced by main().
void test_008 (void)
Definition at line 1010 of file test-rbtree.c.
References compare(), rbtree_create(), rbtree_destroy(), rbtree_in_order_first(), rbtree_in_order_next(), rbtree_insert(), rbtree_key(), and rbtree_value().
Referenced by main().
void test_delete_permutation (rbtree_t * t, int s, int * k, double * d, int index, unsigned long long b)
Definition at line 210 of file test-rbtree.c.
References rbtree_clone(), rbtree_destroy(), rbtree_find(), rbtree_remove(), and test_tree().
Referenced by test_insert_permutation().
void test_in_order_traversal (rbtree_t * t)
Definition at line 338 of file test-rbtree.c.
References rbtree_in_order_first(), rbtree_in_order_last(), rbtree_in_order_next(), rbtree_in_order_prev(), rbtree_key(), and rbtree_value().
Referenced by test_004(), and test_005().
void test_insert_permutation (rbtree_t * t, int s, int * k, double * d, int index, int bits_left, unsigned long long b)
Definition at line 241 of file test-rbtree.c.
References rbtree_find(), rbtree_insert(), rbtree_remove(), test_delete_permutation(), and test_tree().
Referenced by test_003().
void test_tree (rbtree_t * t, int s, int k[], double d[], unsigned long long b)
Definition at line 173 of file test-rbtree.c.
References rbtree_find(), rbtree_in_order_first(), rbtree_in_order_next(), rbtree_key(), and rbtree_value().
Referenced by test_delete_permutation(), and test_insert_permutation().
int write_key (FILE * fout, void * key)
Definition at line 60 of file test-rbtree.c.