cgdsa-c: test-str.c File Reference
test-str.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include <unistd.h>
#include "str.h"
Functions
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Definition at line 9 of file test-str.c.
References dllist_destroy(), dllist_first(), dllist_next(), dllist_size(), dllist_value(), str_append(), str_assign(), str_capacity(), str_caseless_compare(), str_caseless_find(), str_caseless_rfind(), str_clear(), str_compare(), str_create(), str_destroy(), str_erase(), str_find(), str_find_char(), str_find_not_char(), str_getline(), str_insert(), str_join(), str_len(), str_prepend(), str_replace(), str_reserve(), str_rfind(), str_rfind_char(), str_rfind_not_char(), str_shrink_reserve(), str_split(), str_substr(), and str_swap().