cgdsa-c: test-tree.c File Reference
test-tree.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <string.h>
#include "tree.h"
Functions
int __write_node_key (FILE *fout, void *key)
int __write_node_value_char (FILE *fout, void *value)
int __write_node_value_double (FILE *fout, void *value)
int compare (const void *a1, const void *a2)
void test_tree (tree_t *t, int s, int k[], double d[], unsigned long long b)
void test_delete_permutation (tree_t *t, int s, int *k, double *d, int index, unsigned long long b)
void test_insert_permutation (tree_t *t, int s, int *k, double *d, int index, int bits_left, unsigned long long b)
void test_001 (void)
void test_in_order_traversal (tree_t *t)
void test_002 (void)
void test_003 (void)
void test_004 (void)
void test_005 (void)
int main (int argc, char **argv)
Function Documentation
int __write_node_key (FILE * fout, void * key)
Definition at line 8 of file test-tree.c.
int __write_node_value_char (FILE * fout, void * value)
Definition at line 17 of file test-tree.c.
int __write_node_value_double (FILE * fout, void * value)
Definition at line 25 of file test-tree.c.
int compare (const void * a1, const void * a2)
Definition at line 33 of file test-tree.c.
Referenced by test_001(), test_002(), test_003(), test_004(), and test_005().
int main (int argc, char ** argv)
Definition at line 845 of file test-tree.c.
References test_001(), test_002(), test_003(), test_004(), and test_005().
void test_001 (void)
Definition at line 150 of file test-tree.c.
References compare(), test_insert_permutation(), tree_create(), and tree_destroy().
Referenced by main().
void test_002 (void)
Definition at line 213 of file test-tree.c.
References compare(), test_in_order_traversal(), tree_clone(), tree_create(), tree_destroy(), tree_find(), tree_insert(), tree_remove(), and trees_are_identical().
Referenced by main().
void test_003 (void)
Definition at line 264 of file test-tree.c.
References compare(), test_in_order_traversal(), tree_clone(), tree_create(), tree_destroy(), tree_insert(), tree_left(), tree_right(), tree_rotate_left(), tree_rotate_right(), and tree_top().
Referenced by main().
void test_004 (void)
Definition at line 326 of file test-tree.c.
References compare(), tree_create(), tree_destroy(), tree_in_order_first(), tree_in_order_last(), tree_in_order_next(), tree_in_order_prev(), tree_insert(), tree_level_order_first(), tree_level_order_last(), tree_level_order_next(), tree_level_order_prev(), tree_post_order_first(), tree_post_order_last(), tree_post_order_next(), tree_post_order_prev(), tree_pre_order_first(), tree_pre_order_last(), tree_pre_order_next(), tree_pre_order_prev(), and tree_value().
Referenced by main().
void test_005 (void)
Definition at line 675 of file test-tree.c.
References compare(), tree_create(), tree_destroy(), tree_insert(), tree_is_balanced(), tree_is_complete(), tree_is_degenerate(), tree_is_full(), tree_max_depth(), tree_min_depth(), tree_size(), and tree_top().
Referenced by main().
void test_delete_permutation (tree_t * t, int s, int * k, double * d, int index, unsigned long long b)
Definition at line 80 of file test-tree.c.
References test_tree(), tree_clone(), tree_destroy(), tree_find(), and tree_remove().
Referenced by test_insert_permutation().
void test_in_order_traversal (tree_t * t)
Definition at line 181 of file test-tree.c.
References tree_in_order_first(), tree_in_order_last(), tree_in_order_next(), tree_in_order_prev(), tree_key(), and tree_value().
Referenced by test_002(), and test_003().
void test_insert_permutation (tree_t * t, int s, int * k, double * d, int index, int bits_left, unsigned long long b)
Definition at line 111 of file test-tree.c.
References test_delete_permutation(), test_tree(), tree_find(), tree_insert(), and tree_remove().
Referenced by test_001().
void test_tree (tree_t * t, int s, int k[], double d[], unsigned long long b)
Definition at line 43 of file test-tree.c.
References tree_find(), tree_in_order_first(), tree_in_order_next(), tree_key(), and tree_value().
Referenced by test_delete_permutation(), and test_insert_permutation().