cgdsa-c: test-dllist.c File Reference
test-dllist.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include "dllist.h"
Functions
int compare (const void *a1, const void *a2)
int * dup_int (int i)
int main (int argc, char **argv)
Function Documentation
int compare (const void * a1, const void * a2)
Definition at line 9 of file test-dllist.c.
Referenced by dllist_create(), main(), rbtree_create(), test_003(), test_004(), test_005(), test_006(), test_007(), and test_008().
int* dup_int (int i)
Definition at line 26 of file test-dllist.c.
Referenced by main().
int main (int argc, char ** argv)
Definition at line 35 of file test-dllist.c.
References compare(), dllist_attach_node(), dllist_clone(), dllist_create(), dllist_destroy(), dllist_detach_node(), dllist_find(), dllist_first(), dllist_free_node(), dllist_insert(), dllist_insert_after(), dllist_insert_before(), dllist_last(), dllist_next(), dllist_prev(), dllist_push_back(), dllist_push_front(), dllist_remove(), dllist_sentinel(), dllist_size(), dllist_sort(), dllist_value(), dllists_are_identical(), and dup_int().