cgdsa-c: tree.c File Reference
tree.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include "tree.h"
Data Structures
struct __trnode_t
struct __tree_t
Typedefs
typedef struct __trnode_t trnode_t
typedef struct __tree_t tree_t
Functions
int __tree_is_leaf (trnode_t *n)
trnode_t * __tree_grandparent (trnode_t *n)
trnode_t * __tree_sibling (trnode_t *n)
trnode_t * __tree_uncle (trnode_t *n)
tree_t * tree_create (tree_compare compare, tree_free free)
Create a new tree.
int tree_clear (tree_t *t)
Empty the tree by destroying all of it's nodes.
trnode_t * __tree_new_node (void *key, void *value, trnode_t *left, trnode_t *right)
trnode_t * tree_find (tree_t *t, void *key)
Given a tree and a key, search the tree for a node with the given key.
void __tree_replace_node (tree_t *t, trnode_t *oldn, trnode_t *newn)
int tree_rotate_left (trnode_t *n)
Given a node, rotate left about that node so that the given node becomes the left parent of what was once it's parent.
int tree_rotate_right (trnode_t *n)
Given a node, rotate right about that node so that the given node becomes the right parent of what was once it's parent.
trnode_t * tree_attach_node (tree_t *t, trnode_t *node)
Attach a node to the tree.
int tree_insert (tree_t *t, void *key, void *value)
Create a new node with the given key/value pair, and insert it into the tree.
trnode_t * __tree_maximum_node (trnode_t *n)
trnode_t * tree_detach_node (tree_t *t, trnode_t *n)
Detach the given node from the tree.
int tree_remove (tree_t *t, trnode_t *n)
Given a tree and a node, remove the node from the tree.
size_t tree_size (tree_t *t)
Return the number of nodes in the tree.
trnode_t * __tree_apply_function (trnode_t *n, tree_func func)
void __tree_destroy_nodes (tree_t *t, trnode_t *n)
tree_t * tree_destroy (tree_t *t)
Destroy a tree and free all nodes, keys, and values.
int __tree_clone_node (tree_t *t, trnode_t *n)
tree_t * tree_clone (tree_t *t)
Make a copy of a tree.
trnode_t * tree_apply (tree_t *t, tree_func func)
Apply a transformation to each value of each node in the tree.
int __tree_write_gv_node (trnode_t *n, FILE *fout, int(*write_node_key)(FILE *fout, void *key), int(*write_node_value)(FILE *fout, void *value))
int tree_write_gv (tree_t *t, char *filename, int(*write_node_key)(FILE *fout, void *key), int(*write_node_value)(FILE *fout, void *value))
Write a tree as a graphviz dot file.
void * tree_key (trnode_t *n)
Return the key from a node.
void * tree_value (trnode_t *n)
Return the value from a node.
trnode_t * tree_top (tree_t *t)
Return the root node of a tree.
trnode_t * tree_left (trnode_t *n)
Return the left child of a node.
trnode_t * tree_right (trnode_t *n)
Return the right child of a node.
trnode_t * tree_parent (trnode_t *n)
Return the parent node of a node.
trnode_t * tree_in_order_first (tree_t *t)
Given a tree, return the first node for in-order traversal.
trnode_t * tree_in_order_last (tree_t *t)
Given a tree, return the first node for reverse in-order traversal.
trnode_t * tree_in_order_next (trnode_t *n)
Given a node, return the next node via in-order traversal.
trnode_t * tree_in_order_prev (trnode_t *n)
Given a node, return the previous node via reverse in-order traversal.
trnode_t * tree_pre_order_first (tree_t *t)
Given a tree, return the first node for pre-order traversal.
trnode_t * tree_pre_order_last (tree_t *t)
Given a tree, return the first node for reverse pre-order traversal.
trnode_t * tree_pre_order_next (trnode_t *n)
Given a node, return the next node via pre-order traversal.
trnode_t * tree_pre_order_prev (trnode_t *n)
Given a node, return the previous node via reverse in-order traversal.
trnode_t * tree_post_order_first (tree_t *t)
Given a tree, return the first node for post-order traversal.
trnode_t * tree_post_order_last (tree_t *t)
Given a tree, return the first node for reverse post-order traversal.
trnode_t * tree_post_order_next (trnode_t *n)
Given a node, return the next node via post-order traversal.
trnode_t * tree_post_order_prev (trnode_t *n)
Given a node, return the previous node via reverse post-order traversal.
int trees_are_identical (tree_t *t1, tree_t *t2)
Determine if two trees are identical.
trnode_t * tree_level_order_first (tree_t *t)
Given a tree, return the first node for level-order traversal.
size_t __trnode_t_depth (trnode_t *n)
trnode_t * tree_level_order_last (tree_t *t)
Given a tree, return the first node for reverse level-order traversal.
trnode_t * tree_level_order_next (trnode_t *n)
Given a node, return the next node via level-order traversal.
trnode_t * tree_level_order_prev (trnode_t *n)
Given a node, return the previous node via reverse level-order traversal.
size_t __tree_max_depth (trnode_t *n)
size_t tree_max_depth (trnode_t *n)
Return the maximum depth of the tree.
size_t __tree_min_depth (trnode_t *n)
size_t tree_min_depth (trnode_t *n)
Return the minimum depth of the tree.
int tree_is_full (tree_t *t)
Determine if the tree is full, meaning that all nodes have either two children, or no children.
int tree_is_perfect (tree_t *t)
Determine if the tree is perfect, meaning that the tree is full and has a full bottom level.
int tree_is_complete (tree_t *t)
Determine if the tree is complete, meaning that the tree is full down to the bottom level, and all the nodes on the bottom level are as far left as possible.
int tree_is_balanced (tree_t *t)
Determine if the tree is balanced, meaning that the depth of the left and right subtrees under the top node differ by at most 1.
int tree_is_degenerate (tree_t *t)
Determine if the tree is degenerate, meaning that each parent node has only one child node.
Typedef Documentation
typedef struct __tree_t tree_t
typedef struct __trnode_t trnode_t
Function Documentation
trnode_t* __tree_apply_function (trnode_t * n, tree_func func)
Definition at line 424 of file tree.c.
References __trnode_t::key, __trnode_t::left, __trnode_t::right, and __trnode_t::value.
Referenced by tree_apply().
int __tree_clone_node (tree_t * t, trnode_t * n)
Definition at line 461 of file tree.c.
References tree_insert(), tree_key(), tree_left(), tree_right(), and tree_value().
Referenced by tree_clone().
void __tree_destroy_nodes (tree_t * t, trnode_t * n)
Definition at line 441 of file tree.c.
References __tree_t::free, __trnode_t::key, __trnode_t::left, __trnode_t::right, and __trnode_t::value.
Referenced by tree_destroy().
trnode_t* __tree_grandparent (trnode_t * n)
Definition at line 62 of file tree.c.
References __trnode_t::parent.
int __tree_is_leaf (trnode_t * n)
Definition at line 55 of file tree.c.
References __trnode_t::left, and __trnode_t::right.
Referenced by tree_is_balanced(), and tree_is_complete().
size_t __tree_max_depth (trnode_t * n)
Definition at line 971 of file tree.c.
References __trnode_t::left, and __trnode_t::right.
Referenced by tree_max_depth().
trnode_t* __tree_maximum_node (trnode_t * n)
Definition at line 373 of file tree.c.
References __trnode_t::right.
Referenced by tree_detach_node().
size_t __tree_min_depth (trnode_t * n)
Definition at line 996 of file tree.c.
References __trnode_t::left, and __trnode_t::right.
Referenced by tree_min_depth().
trnode_t* __tree_new_node (void * key, void * value, trnode_t * left, trnode_t * right)
Definition at line 117 of file tree.c.
References __trnode_t::key, __trnode_t::left, __trnode_t::parent, __trnode_t::right, and __trnode_t::value.
Referenced by tree_insert().
void __tree_replace_node (tree_t * t, trnode_t * oldn, trnode_t * newn)
Definition at line 167 of file tree.c.
References __trnode_t::left, __trnode_t::parent, __trnode_t::right, and __tree_t::root.
Referenced by tree_detach_node().
trnode_t* __tree_sibling (trnode_t * n)
Definition at line 70 of file tree.c.
References __trnode_t::left, __trnode_t::parent, and __trnode_t::right.
Referenced by __tree_uncle().
trnode_t* __tree_uncle (trnode_t * n)
Definition at line 80 of file tree.c.
References __tree_sibling(), and __trnode_t::parent.
int __tree_write_gv_node (trnode_t * n, FILE * fout, int(*)(FILE *fout, void *key) write_node_key, int(*)(FILE *fout, void *value) write_node_value)
Definition at line 501 of file tree.c.
References __trnode_t::key, __trnode_t::left, __trnode_t::parent, __trnode_t::right, and __trnode_t::value.
Referenced by tree_write_gv().
size_t __trnode_t_depth (trnode_t * n)
Definition at line 876 of file tree.c.
References tree_parent().
Referenced by tree_level_order_last(), tree_level_order_next(), and tree_level_order_prev().
trnode_t* tree_apply (tree_t * t, tree_func func)
Apply a transformation to each value of each node in the tree.
Return value:
Success: NULL
Failure: trnode_t * pointer to the node on which func() failed
Definition at line 492 of file tree.c.
References __tree_apply_function(), and __tree_t::root.
trnode_t* tree_attach_node (tree_t * t, trnode_t * n)
Attach a node to the tree.
Return value:
Success: tree_t * pointer to the newly attached node
Failure: NULL
Notes: Be aware that the trnode_t * pointer passed back may have a different address than the pointer passed in. Therefore proper usage should be:
n = tree_attach_node(t, n); if (n == NULL) { // Attach failed }
Notes: Be aware that when inserting a node with a duplicate key, the original node's key/value pair are removed and replaced with the new key/value pair.
Definition at line 304 of file tree.c.
References __tree_t::compare, __tree_t::free, __trnode_t::key, __trnode_t::left, __trnode_t::parent, __trnode_t::right, __tree_t::root, __tree_t::size, and __trnode_t::value.
Referenced by tree_insert().
int tree_clear (tree_t * t)
Empty the tree by destroying all of it's nodes.
Return value:
Success: 1
Failure: 0
Definition at line 101 of file tree.c.
References __trnode_t::parent, tree_post_order_first(), tree_post_order_next(), and tree_remove().
tree_t* tree_clone (tree_t * t)
Make a copy of a tree.
Return value:
Success: tree_t * pointer to the cloned tree
Failure: NULL
Notes: Be aware that cloning a tree merely copies the key and value pointers. It does not create copies of what they key and value pointers point to.
Definition at line 476 of file tree.c.
References __tree_clone_node(), __tree_t::compare, __tree_t::free, tree_create(), tree_destroy(), and tree_top().
Referenced by test_002(), test_003(), and test_delete_permutation().
tree_t* tree_create (tree_compare compare, tree_free free)
Create a new tree.
Compare is a pointer to a function used to compare void
keys. Compare cannot be NULL. Free is a pointer to a function to call when destroying nodes. Free is responsible for properly releasing any memory used for the key and value stored by the node.
Return value:
Success: A tree * pointer
Failure: NULL
Definition at line 88 of file tree.c.
References compare(), __tree_t::compare, __tree_t::free, __tree_t::root, and __tree_t::size.
Referenced by test_001(), test_002(), test_003(), test_004(), test_005(), and tree_clone().
tree_t* tree_destroy (tree_t * t)
Destroy a tree and free all nodes, keys, and values.
Return value: NULL
Definition at line 452 of file tree.c.
References __tree_destroy_nodes(), and __tree_t::root.
Referenced by test_001(), test_002(), test_003(), test_004(), test_005(), test_delete_permutation(), and tree_clone().
trnode_t* tree_detach_node (tree_t * t, trnode_t * n)
Detach the given node from the tree.
Return value:
Success: trnode_t * pointer to the new detached node
Failure: NULL
Notes: Be aware that the trnode_t * pointer passed back may have a different address than the pointer passed in. Therefore proper usage should be:
n = tree_detach_node(t, n); if (n == NULL) { // Detach failed }
Definition at line 382 of file tree.c.
References __tree_maximum_node(), __tree_replace_node(), __trnode_t::key, __trnode_t::left, __trnode_t::parent, __trnode_t::right, __tree_t::size, and __trnode_t::value.
Referenced by tree_remove().
trnode_t* tree_find (tree_t * t, void * key)
Given a tree and a key, search the tree for a node with the given key.
Return value:
Success: trnode_t *
Failure: NULL
Definition at line 137 of file tree.c.
References __tree_t::compare, __trnode_t::key, __trnode_t::left, __trnode_t::right, and __tree_t::root.
Referenced by test_002(), test_delete_permutation(), test_insert_permutation(), and test_tree().
trnode_t* tree_in_order_first (tree_t * t)
Given a tree, return the first node for in-order traversal.
Return value:
Success: trnode_t *
Failure: NULL – The tree is empty
Definition at line 610 of file tree.c.
References __trnode_t::left, and __tree_t::root.
Referenced by test_004(), test_in_order_traversal(), test_tree(), tree_is_balanced(), tree_is_full(), and trees_are_identical().
trnode_t* tree_in_order_last (tree_t * t)
Given a tree, return the first node for reverse in-order traversal.
Return value:
Success: trnode_t *
Failure: NULL – The tree is empty
Definition at line 625 of file tree.c.
References __trnode_t::right, and __tree_t::root.
Referenced by test_004(), and test_in_order_traversal().
trnode_t* tree_in_order_next (trnode_t * n)
Given a node, return the next node via in-order traversal.
Return value:
Success: trnode_t *
Failure: NULL – There is no next node
Definition at line 640 of file tree.c.
References __trnode_t::left, __trnode_t::parent, and __trnode_t::right.
Referenced by test_004(), test_in_order_traversal(), test_tree(), tree_is_balanced(), tree_is_full(), tree_level_order_next(), and trees_are_identical().
trnode_t* tree_in_order_prev (trnode_t * n)
Given a node, return the previous node via reverse in-order traversal.
Return value:
Success: trnode_t *
Failure: NULL – There is no previous node
Definition at line 668 of file tree.c.
References __trnode_t::left, __trnode_t::parent, and __trnode_t::right.
Referenced by test_004(), test_in_order_traversal(), and tree_level_order_prev().
int tree_insert (tree_t * t, void * key, void * value)
Create a new node with the given key/value pair, and insert it into the tree.
Return value:
Success: 1
Failure: 0
Notes: Be aware that when inserting a duplicate key, the original node is removed and replaced with the new key/value pair.
Definition at line 358 of file tree.c.
References __tree_new_node(), and tree_attach_node().
Referenced by __tree_clone_node(), test_002(), test_003(), test_004(), test_005(), and test_insert_permutation().
int tree_is_balanced (tree_t * t)
Determine if the tree is balanced, meaning that the depth of the left and right subtrees under the top node differ by at most 1.
Return value:
Success: 1 – tree is balanced
Failure: 0 – tree is not balanced
Definition at line 1140 of file tree.c.
References __tree_is_leaf(), tree_in_order_first(), tree_in_order_next(), tree_left(), tree_max_depth(), and tree_right().
Referenced by test_005().
int tree_is_complete (tree_t * t)
Determine if the tree is complete, meaning that the tree is full down to the bottom level, and all the nodes on the bottom level are as far left as possible.
Return value:
Success: 1 – tree is complete
Failure: 0 – tree is not complete
Definition at line 1047 of file tree.c.
References __tree_is_leaf(), tree_left(), tree_parent(), tree_right(), and tree_top().
Referenced by test_005().
int tree_is_degenerate (tree_t * t)
Determine if the tree is degenerate, meaning that each parent node has only one child node.
Return value:
Success: 1 – tree is degenerate
Failure: 0 – tree is not degenerate
Definition at line 1161 of file tree.c.
References tree_max_depth(), tree_size(), and tree_top().
Referenced by test_005().
int tree_is_full (tree_t * t)
Determine if the tree is full, meaning that all nodes have either two children, or no children.
Return value:
Success: 1 – tree is full
Failure: 0 – tree is not full
Definition at line 1021 of file tree.c.
References __trnode_t::left, __trnode_t::right, tree_in_order_first(), and tree_in_order_next().
Referenced by test_005(), and tree_is_perfect().
int tree_is_perfect (tree_t * t)
Determine if the tree is perfect, meaning that the tree is full and has a full bottom level.
Return value:
Success: 1 – tree is perfect
Failure: 0 – tree is not perfect
Definition at line 1040 of file tree.c.
References tree_is_full(), tree_max_depth(), tree_min_depth(), and tree_top().
void* tree_key (trnode_t * n)
Return the key from a node.
Definition at line 580 of file tree.c.
References __trnode_t::key.
Referenced by __tree_clone_node(), test_in_order_traversal(), and test_tree().
trnode_t* tree_left (trnode_t * n)
Return the left child of a node.
Return value:
Success: trnode_t *
Failure: NULL – The node has no left child
Definition at line 595 of file tree.c.
References __trnode_t::left.
Referenced by __tree_clone_node(), test_003(), tree_is_balanced(), and tree_is_complete().
trnode_t* tree_level_order_first (tree_t * t)
Given a tree, return the first node for level-order traversal.
Return value:
Success: trnode_t *
Failure: NULL – The tree is empty
Definition at line 869 of file tree.c.
References __tree_t::root.
Referenced by test_004().
trnode_t* tree_level_order_last (tree_t * t)
Given a tree, return the first node for reverse level-order traversal.
Return value:
Success: trnode_t *
Failure: NULL – The tree is empty
Definition at line 887 of file tree.c.
References __trnode_t_depth(), tree_post_order_last(), tree_post_order_prev(), and tree_top().
Referenced by test_004().
trnode_t* tree_level_order_next (trnode_t * n)
Given a node, return the next node via level-order traversal.
Return value:
Success: trnode_t *
Failure: NULL – There is no next node
Definition at line 911 of file tree.c.
References __trnode_t_depth(), __trnode_t::left, __trnode_t::parent, tree_in_order_next(), and tree_post_order_next().
Referenced by test_004().
trnode_t* tree_level_order_prev (trnode_t * n)
Given a node, return the previous node via reverse level-order traversal.
Return value:
Success: trnode_t *
Failure: NULL – There is no previous node
Definition at line 941 of file tree.c.
References __trnode_t_depth(), __trnode_t::parent, __trnode_t::right, tree_in_order_prev(), and tree_post_order_prev().
Referenced by test_004().
size_t tree_max_depth (trnode_t * n)
Return the maximum depth of the tree.
Return value:
Success: >= 0
Failure: 0
Definition at line 987 of file tree.c.
References __tree_max_depth().
Referenced by test_005(), tree_is_balanced(), tree_is_degenerate(), and tree_is_perfect().
size_t tree_min_depth (trnode_t * n)
Return the minimum depth of the tree.
Return value:
Success: >= 0
Failure: 0
Definition at line 1012 of file tree.c.
References __tree_min_depth().
Referenced by test_005(), and tree_is_perfect().
trnode_t* tree_parent (trnode_t * n)
Return the parent node of a node.
Return value:
Success: trnode_t *
Failure: NULL – The node has no parent
Definition at line 605 of file tree.c.
References __trnode_t::parent.
Referenced by __trnode_t_depth(), and tree_is_complete().
trnode_t* tree_post_order_first (tree_t * t)
Given a tree, return the first node for post-order traversal.
Return value:
Success: trnode_t *
Failure: NULL – The tree is empty
Definition at line 769 of file tree.c.
References __trnode_t::left, and __tree_t::root.
Referenced by test_004(), and tree_clear().
trnode_t* tree_post_order_last (tree_t * t)
Given a tree, return the first node for reverse post-order traversal.
Return value:
Success: trnode_t *
Failure: NULL – The tree is empty
Definition at line 784 of file tree.c.
References __tree_t::root.
Referenced by test_004(), and tree_level_order_last().
trnode_t* tree_post_order_next (trnode_t * n)
Given a node, return the next node via post-order traversal.
Return value:
Success: trnode_t *
Failure: NULL – There is no next node
Definition at line 791 of file tree.c.
References __trnode_t::left, __trnode_t::parent, and __trnode_t::right.
Referenced by test_004(), tree_clear(), and tree_level_order_next().
trnode_t* tree_post_order_prev (trnode_t * n)
Given a node, return the previous node via reverse post-order traversal.
Return value:
Success: trnode_t *
Failure: NULL – There is no previous node
Definition at line 812 of file tree.c.
References __trnode_t::left, __trnode_t::parent, and __trnode_t::right.
Referenced by test_004(), tree_level_order_last(), and tree_level_order_prev().
trnode_t* tree_pre_order_first (tree_t * t)
Given a tree, return the first node for pre-order traversal.
Return value:
Success: trnode_t *
Failure: NULL – The tree is empty
Definition at line 696 of file tree.c.
References __tree_t::root.
Referenced by test_004().
trnode_t* tree_pre_order_last (tree_t * t)
Given a tree, return the first node for reverse pre-order traversal.
Return value:
Success: trnode_t *
Failure: NULL – The tree is empty
Definition at line 705 of file tree.c.
References __trnode_t::right, and __tree_t::root.
Referenced by test_004().
trnode_t* tree_pre_order_next (trnode_t * n)
Given a node, return the next node via pre-order traversal.
Return value:
Success: trnode_t *
Failure: NULL – There is no next node
Definition at line 719 of file tree.c.
References __trnode_t::left, __trnode_t::parent, and __trnode_t::right.
Referenced by test_004().
trnode_t* tree_pre_order_prev (trnode_t * n)
Given a node, return the previous node via reverse in-order traversal.
Return value:
Success: trnode_t *
Failure: NULL – There is no previous node
Definition at line 747 of file tree.c.
References __trnode_t::left, __trnode_t::parent, and __trnode_t::right.
Referenced by test_004().
int tree_remove (tree_t * t, trnode_t * n)
Given a tree and a node, remove the node from the tree.
Return value:
Success: 1
Failure: 0
Definition at line 409 of file tree.c.
References __tree_t::free, __trnode_t::key, tree_detach_node(), and __trnode_t::value.
Referenced by test_002(), test_delete_permutation(), test_insert_permutation(), and tree_clear().
trnode_t* tree_right (trnode_t * n)
Return the right child of a node.
Return value:
Success: trnode_t *
Failure: NULL – The node has no right child
Definition at line 600 of file tree.c.
References __trnode_t::right.
Referenced by __tree_clone_node(), test_003(), tree_is_balanced(), and tree_is_complete().
int tree_rotate_left (trnode_t * n)
Given a node, rotate left about that node so that the given node becomes the left parent of what was once it's parent.
Return value:
Success: 1
Failure: 0
Definition at line 223 of file tree.c.
References __trnode_t::left, __trnode_t::parent, and __trnode_t::right.
Referenced by test_003().
int tree_rotate_right (trnode_t * n)
Given a node, rotate right about that node so that the given node becomes the right parent of what was once it's parent.
Return value:
Success: 1
Failure: 0
Definition at line 263 of file tree.c.
References __trnode_t::left, __trnode_t::parent, and __trnode_t::right.
Referenced by test_003().
size_t tree_size (tree_t * t)
Return the number of nodes in the tree.
Definition at line 419 of file tree.c.
References __tree_t::size.
Referenced by test_005(), and tree_is_degenerate().
trnode_t* tree_top (tree_t * t)
Return the root node of a tree.
Return value:
Success: trnode_t *
Failure: NULL – The tree is empty
Definition at line 590 of file tree.c.
References __tree_t::root.
Referenced by test_003(), test_005(), tree_clone(), tree_is_complete(), tree_is_degenerate(), tree_is_perfect(), and tree_level_order_last().
void* tree_value (trnode_t * n)
Return the value from a node.
Definition at line 585 of file tree.c.
References __trnode_t::value.
Referenced by __tree_clone_node(), test_004(), test_in_order_traversal(), and test_tree().
int tree_write_gv (tree_t * t, char * filename, int(*)(FILE *fout, void *key) write_node_key, int(*)(FILE *fout, void *value) write_node_value)
Write a tree as a graphviz dot file.
Return value:
Success: 1
Failure: 0
Definition at line 551 of file tree.c.
References __tree_write_gv_node(), and __tree_t::root.
int trees_are_identical (tree_t * t1, tree_t * t2)
Determine if two trees are identical.
Return value:
Success: 1 – Trees are identical
Failure: 0 – Trees differ
Definition at line 840 of file tree.c.
References __tree_t::compare, __tree_t::size, tree_in_order_first(), tree_in_order_next(), and __trnode_t::value.
Referenced by test_002().